import { EXTRA_RECIPES } from './recipes-extra.js';

// Base de recettes healthy intégrée.
// Quantités indiquées POUR 1 PORTION. keeps = jours de conservation au frigo.
// Format ingrédient : [nom, quantité, unité ('' = pièce), rayon]

const R = (id, name, o) => {
  const { ing, ...rest } = o;
  return {
    id: 's-' + id,
    name,
    ...rest,
    ingredients: ing.map(([n, qty, unit, cat]) => ({ name: n, qty, unit, cat })),
  };
};

const BASE_RECIPES = [
  R('poulet-curry-coco', 'Poulet curry-coco, épinards & riz basmati', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 35, kcal: 560, keeps: 4, freezable: true,
    ing: [['blanc de poulet', 130, 'g', 'proteines'], ['lait de coco', 60, 'ml', 'epicerie'], ['oignon', 0.5, '', 'legumes'],
      ['épinards frais', 60, 'g', 'legumes'], ['riz basmati', 70, 'g', 'feculents'], ['ail', 1, 'gousse', 'legumes'],
      ['curry en poudre', 1, 'c.à.c', 'placard'], ['huile d\'olive', 0.5, 'c.à.s', 'placard']],
    steps: ['Cuire le riz.', 'Faire revenir oignon et ail émincés dans l\'huile, ajouter le poulet en dés et le curry.',
      'Verser le lait de coco, mijoter 15 min.', 'Ajouter les épinards 2 min avant la fin.'],
  }),
  R('chili-sin-carne', 'Chili sin carne & riz complet', {
    tags: ['vegan', 'sans-gluten'], main: 'legumineuses', time: 40, kcal: 520, keeps: 5, freezable: true,
    ing: [['haricots rouges cuits', 120, 'g', 'feculents'], ['lentilles corail', 40, 'g', 'feculents'], ['tomates concassées', 150, 'g', 'epicerie'],
      ['poivron', 0.5, '', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['maïs en conserve', 50, 'g', 'epicerie'],
      ['riz complet', 60, 'g', 'feculents'], ['cumin', 1, 'c.à.c', 'placard'], ['paprika fumé', 0.5, 'c.à.c', 'placard']],
    steps: ['Cuire le riz complet.', 'Faire revenir oignon et poivron, ajouter les épices.',
      'Ajouter tomates, lentilles corail et un verre d\'eau, mijoter 20 min.', 'Ajouter haricots et maïs, réchauffer 5 min.'],
  }),
  R('saumon-patate-douce', 'Saumon rôti, patate douce & brocoli', {
    tags: ['poisson', 'sans-gluten'], main: 'saumon', time: 35, kcal: 540, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 130, 'g', 'proteines'], ['patate douce', 200, 'g', 'legumes'], ['brocoli', 150, 'g', 'legumes'],
      ['citron', 0.25, '', 'legumes'], ['huile d\'olive', 1, 'c.à.s', 'placard']],
    steps: ['Couper la patate douce en cubes, rôtir 25 min à 200 °C avec la moitié de l\'huile.',
      'Ajouter le saumon et le brocoli en fleurettes sur la plaque pour les 12 dernières minutes.', 'Arroser de citron.'],
  }),
  R('bowl-quinoa-feta', 'Bowl quinoa, pois chiches rôtis & feta', {
    tags: ['vegetarien', 'sans-gluten'], main: 'legumineuses', time: 30, kcal: 510, keeps: 4, freezable: false,
    ing: [['quinoa', 60, 'g', 'feculents'], ['pois chiches cuits', 100, 'g', 'feculents'], ['concombre', 0.3, '', 'legumes'],
      ['tomates cerises', 80, 'g', 'legumes'], ['feta', 40, 'g', 'cremerie'], ['citron', 0.25, '', 'legumes'],
      ['huile d\'olive', 1, 'c.à.s', 'placard'], ['paprika', 0.5, 'c.à.c', 'placard']],
    steps: ['Cuire le quinoa.', 'Rôtir les pois chiches 20 min à 200 °C avec paprika et un filet d\'huile.',
      'Couper concombre et tomates.', 'Assembler, émietter la feta, assaisonner citron-huile au moment de servir.'],
  }),
  R('dahl-lentilles', 'Dahl de lentilles corail & riz', {
    tags: ['vegan', 'sans-gluten'], main: 'legumineuses', time: 30, kcal: 490, keeps: 5, freezable: true,
    ing: [['lentilles corail', 80, 'g', 'feculents'], ['lait de coco', 50, 'ml', 'epicerie'], ['tomates concassées', 100, 'g', 'epicerie'],
      ['oignon', 0.5, '', 'legumes'], ['gingembre frais', 5, 'g', 'legumes'], ['épinards frais', 50, 'g', 'legumes'],
      ['riz basmati', 50, 'g', 'feculents'], ['curcuma', 0.5, 'c.à.c', 'placard'], ['cumin', 0.5, 'c.à.c', 'placard']],
    steps: ['Faire revenir oignon et gingembre râpé avec les épices.', 'Ajouter lentilles, tomates, lait de coco et 2 fois leur volume d\'eau.',
      'Mijoter 20 min en remuant.', 'Incorporer les épinards, servir avec le riz.'],
  }),
  R('boulettes-dinde', 'Boulettes de dinde, sauce tomate & pâtes complètes', {
    tags: ['viande'], main: 'dinde', time: 40, kcal: 590, keeps: 4, freezable: true,
    ing: [['dinde hachée', 130, 'g', 'proteines'], ['flocons d\'avoine', 15, 'g', 'feculents'], ['œufs', 0.25, '', 'cremerie'],
      ['coulis de tomate', 150, 'g', 'epicerie'], ['pâtes complètes', 80, 'g', 'feculents'], ['parmesan', 10, 'g', 'cremerie'],
      ['ail', 1, 'gousse', 'legumes'], ['herbes de Provence', 0.5, 'c.à.c', 'placard']],
    steps: ['Mélanger dinde, avoine, œuf, ail haché et herbes ; former des boulettes.', 'Les dorer à la poêle puis ajouter le coulis, mijoter 15 min.',
      'Cuire les pâtes.', 'Servir avec le parmesan.'],
  }),
  R('tofu-soba', 'Tofu sauté, légumes croquants & nouilles soba', {
    tags: ['vegan'], main: 'tofu', time: 25, kcal: 480, keeps: 3, freezable: false,
    ing: [['tofu ferme', 120, 'g', 'proteines'], ['nouilles soba', 70, 'g', 'feculents'], ['brocoli', 100, 'g', 'legumes'],
      ['carotte', 0.5, '', 'legumes'], ['gingembre frais', 5, 'g', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'],
      ['graines de sésame', 5, 'g', 'epicerie'], ['huile de sésame', 0.5, 'c.à.s', 'placard']],
    steps: ['Cuire les soba, rincer à l\'eau froide.', 'Dorer le tofu en cubes à la poêle.',
      'Sauter brocoli et carotte en julienne avec le gingembre 5 min.', 'Mélanger le tout avec la sauce soja, parsemer de sésame.'],
  }),
  R('ratatouille-quinoa', 'Ratatouille, quinoa & œuf mollet', {
    tags: ['vegetarien', 'sans-gluten'], main: 'oeuf', time: 50, kcal: 450, keeps: 5, freezable: true,
    ing: [['courgette', 0.5, '', 'legumes'], ['aubergine', 0.3, '', 'legumes'], ['poivron', 0.5, '', 'legumes'],
      ['tomates', 1, '', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['quinoa', 60, 'g', 'feculents'], ['œufs', 1, '', 'cremerie'],
      ['huile d\'olive', 1, 'c.à.s', 'placard'], ['herbes de Provence', 0.5, 'c.à.c', 'placard']],
    steps: ['Couper tous les légumes en dés.', 'Les faire revenir dans l\'huile puis mijoter 35 min à couvert avec les herbes.',
      'Cuire le quinoa.', 'Cuire les œufs 6 min au moment de servir (ne pas les préparer à l\'avance).'],
  }),
  R('cabillaud-papillote', 'Cabillaud en papillote, courgettes & riz complet', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 30, kcal: 430, keeps: 2, freezable: false,
    ing: [['dos de cabillaud', 140, 'g', 'proteines'], ['courgette', 1, '', 'legumes'], ['tomates cerises', 60, 'g', 'legumes'],
      ['citron', 0.25, '', 'legumes'], ['riz complet', 60, 'g', 'feculents'], ['huile d\'olive', 0.5, 'c.à.s', 'placard'],
      ['herbes de Provence', 0.5, 'c.à.c', 'placard']],
    steps: ['Cuire le riz.', 'Disposer courgette en rondelles, tomates et cabillaud sur du papier cuisson.',
      'Ajouter citron, herbes, huile ; fermer et cuire 18 min à 200 °C.'],
  }),
  R('bolo-lentilles', 'Bolognaise bœuf-lentilles & spaghetti complets', {
    inDish: ['lentilles vertes'], tags: ['viande'], main: 'boeuf', time: 45, kcal: 600, keeps: 4, freezable: true,
    ing: [['bœuf haché 5 %', 100, 'g', 'proteines'], ['lentilles vertes', 40, 'g', 'feculents'], ['carotte', 0.5, '', 'legumes'],
      ['céleri branche', 0.5, '', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['coulis de tomate', 150, 'g', 'epicerie'],
      ['spaghetti complets', 80, 'g', 'feculents'], ['herbes de Provence', 0.5, 'c.à.c', 'placard']],
    steps: ['Faire revenir oignon, carotte et céleri hachés finement.', 'Ajouter le bœuf et le dorer.',
      'Ajouter coulis, lentilles et 1 verre d\'eau par 2 portions, mijoter 30 min.', 'Cuire les spaghetti.'],
  }),
  R('curry-pois-chiches', 'Curry pois chiches & patate douce', {
    tags: ['vegan', 'sans-gluten'], main: 'legumineuses', time: 35, kcal: 500, keeps: 5, freezable: true,
    ing: [['pois chiches cuits', 120, 'g', 'feculents'], ['patate douce', 150, 'g', 'legumes'], ['lait de coco', 50, 'ml', 'epicerie'],
      ['tomates concassées', 100, 'g', 'epicerie'], ['épinards frais', 50, 'g', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['pâte de curry', 1, 'c.à.c', 'epicerie']],
    steps: ['Faire revenir l\'oignon avec la pâte de curry.', 'Ajouter patate douce en dés, tomates, lait de coco ; mijoter 20 min.',
      'Ajouter pois chiches et épinards, cuire 5 min.'],
  }),
  R('taboule-poulet', 'Taboulé de boulgour, poulet grillé & menthe', {
    tags: ['viande'], main: 'poulet', time: 25, kcal: 520, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['boulgour', 60, 'g', 'feculents'], ['concombre', 0.3, '', 'legumes'],
      ['tomates', 1, '', 'legumes'], ['menthe fraîche', 0.2, 'botte', 'legumes'], ['citron', 0.5, '', 'legumes'],
      ['huile d\'olive', 1, 'c.à.s', 'placard']],
    steps: ['Cuire le boulgour, laisser refroidir.', 'Griller le poulet et le trancher.',
      'Mélanger boulgour, légumes en dés, menthe ciselée, citron et huile.', 'Ajouter le poulet.'],
  }),
  R('minestrone', 'Minestrone aux haricots blancs & parmesan', {
    tags: ['vegetarien'], main: 'legumineuses', time: 40, kcal: 400, keeps: 4, freezable: true,
    ing: [['haricots blancs cuits', 80, 'g', 'feculents'], ['carotte', 0.5, '', 'legumes'], ['courgette', 0.5, '', 'legumes'],
      ['poireau', 0.3, '', 'legumes'], ['tomates concassées', 100, 'g', 'epicerie'], ['petites pâtes', 30, 'g', 'feculents'],
      ['parmesan', 10, 'g', 'cremerie'], ['bouillon de légumes (cube)', 0.25, '', 'placard']],
    steps: ['Faire revenir poireau et carotte.', 'Ajouter courgette, tomates, bouillon et 300 ml d\'eau par portion ; cuire 20 min.',
      'Ajouter pâtes et haricots, cuire 10 min.', 'Servir avec le parmesan.'],
  }),
  R('poulet-roti-racines', 'Poulet rôti au citron & légumes racines', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 50, kcal: 550, keeps: 4, freezable: true,
    ing: [['haut de cuisse de poulet', 150, 'g', 'proteines'], ['carotte', 1, '', 'legumes'], ['panais', 0.5, '', 'legumes'],
      ['pommes de terre', 150, 'g', 'feculents'], ['citron', 0.25, '', 'legumes'], ['huile d\'olive', 1, 'c.à.s', 'placard'],
      ['thym', 0.5, 'c.à.c', 'placard']],
    steps: ['Couper les légumes en morceaux, les mélanger avec huile et thym.', 'Poser le poulet dessus, arroser de citron.',
      'Rôtir 40 min à 200 °C.'],
  }),
  R('wok-crevettes', 'Wok de crevettes, pois gourmands & riz', {
    tags: ['poisson'], main: 'crevettes', time: 20, kcal: 460, keeps: 2, freezable: false,
    ing: [['crevettes décortiquées', 120, 'g', 'proteines'], ['poivron', 0.5, '', 'legumes'], ['pois gourmands', 80, 'g', 'legumes'],
      ['riz basmati', 60, 'g', 'feculents'], ['ail', 1, 'gousse', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'],
      ['huile de sésame', 0.5, 'c.à.s', 'placard']],
    steps: ['Cuire le riz.', 'Sauter ail, poivron et pois gourmands 4 min à feu vif.', 'Ajouter les crevettes 3 min puis la sauce soja.'],
  }),
  R('shakshuka', 'Shakshuka, feta & pain complet', {
    tags: ['vegetarien'], main: 'oeuf', time: 30, kcal: 470, keeps: 3, freezable: true,
    ing: [['œufs', 2, '', 'cremerie'], ['tomates concassées', 200, 'g', 'epicerie'], ['poivron', 0.5, '', 'legumes'],
      ['oignon', 0.5, '', 'legumes'], ['feta', 20, 'g', 'cremerie'], ['pain complet', 60, 'g', 'feculents'],
      ['cumin', 0.5, 'c.à.c', 'placard']],
    steps: ['Préparer la sauce : oignon, poivron, tomates et cumin mijotés 15 min (c\'est elle qu\'on batch).',
      'Le jour J : réchauffer la sauce, y casser les œufs, couvrir 6 min.', 'Émietter la feta, servir avec le pain.'],
  }),
  R('quiche-sans-pate', 'Quiche sans pâte poireaux-champignons', {
    tags: ['vegetarien', 'sans-gluten'], main: 'oeuf', time: 45, kcal: 380, keeps: 3, freezable: true,
    ing: [['œufs', 2, '', 'cremerie'], ['lait demi-écrémé', 80, 'ml', 'cremerie'], ['poireau', 0.5, '', 'legumes'],
      ['champignons de Paris', 80, 'g', 'legumes'], ['gruyère râpé', 20, 'g', 'cremerie'], ['salade verte', 40, 'g', 'legumes']],
    steps: ['Faire fondre poireau et champignons émincés.', 'Battre œufs, lait et gruyère, ajouter les légumes.',
      'Cuire 30 min à 180 °C dans un moule.', 'Servir avec la salade.'],
  }),
  R('buddha-tofu', 'Buddha bowl tofu mariné, edamame & avocat', {
    tags: ['vegan'], main: 'tofu', time: 25, kcal: 560, keeps: 3, freezable: false,
    ing: [['tofu ferme', 100, 'g', 'proteines'], ['riz complet', 60, 'g', 'feculents'], ['edamame surgelés', 60, 'g', 'surgeles'],
      ['carotte', 0.5, '', 'legumes'], ['avocat', 0.5, '', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'],
      ['graines de sésame', 5, 'g', 'epicerie']],
    steps: ['Mariner le tofu en cubes dans la sauce soja puis le dorer.', 'Cuire riz et edamame.',
      'Râper la carotte. Couper l\'avocat au dernier moment.', 'Assembler et parsemer de sésame.'],
  }),
  R('filet-mignon', 'Filet mignon, purée de patate douce & haricots verts', {
    tags: ['viande', 'sans-gluten'], main: 'porc', time: 40, kcal: 520, keeps: 3, freezable: true,
    ing: [['filet mignon de porc', 130, 'g', 'proteines'], ['patate douce', 200, 'g', 'legumes'], ['haricots verts', 150, 'g', 'legumes'],
      ['lait demi-écrémé', 30, 'ml', 'cremerie'], ['huile d\'olive', 0.5, 'c.à.s', 'placard']],
    steps: ['Saisir le filet mignon puis le cuire 20 min à 180 °C.', 'Cuire la patate douce à l\'eau, écraser avec le lait.',
      'Cuire les haricots verts à la vapeur 8 min.', 'Trancher le filet.'],
  }),
  R('choufleur-beluga', 'Chou-fleur rôti, lentilles beluga & sauce yaourt', {
    tags: ['vegetarien', 'sans-gluten'], main: 'legumineuses', time: 35, kcal: 430, keeps: 4, freezable: false,
    ing: [['chou-fleur', 0.3, '', 'legumes'], ['lentilles beluga', 60, 'g', 'feculents'], ['yaourt grec', 50, 'g', 'cremerie'],
      ['citron', 0.25, '', 'legumes'], ['cumin', 0.5, 'c.à.c', 'placard'], ['huile d\'olive', 1, 'c.à.s', 'placard']],
    steps: ['Rôtir le chou-fleur en fleurettes avec huile et cumin 25 min à 200 °C.', 'Cuire les lentilles 20 min.',
      'Mélanger yaourt et citron.', 'Servir la sauce à part (ajoutée au moment de manger).'],
  }),
  R('pates-thon', 'Pâtes complètes au thon, tomates & olives', {
    tags: ['poisson'], main: 'thon', time: 20, kcal: 540, keeps: 3, freezable: false,
    ing: [['thon au naturel', 80, 'g', 'epicerie'], ['pâtes complètes', 80, 'g', 'feculents'], ['tomates cerises', 100, 'g', 'legumes'],
      ['olives noires', 20, 'g', 'epicerie'], ['roquette', 30, 'g', 'legumes'], ['huile d\'olive', 1, 'c.à.s', 'placard']],
    steps: ['Cuire les pâtes.', 'Mélanger avec thon émietté, tomates coupées, olives et huile.', 'Ajouter la roquette au moment de servir.'],
  }),
  R('parmentier-patate-douce', 'Parmentier léger bœuf & patate douce', {
    tags: ['viande', 'sans-gluten'], main: 'boeuf', time: 50, kcal: 540, keeps: 4, freezable: true,
    ing: [['bœuf haché 5 %', 100, 'g', 'proteines'], ['patate douce', 150, 'g', 'legumes'], ['carotte', 1, '', 'legumes'],
      ['oignon', 0.5, '', 'legumes'], ['emmental râpé', 15, 'g', 'cremerie'], ['salade verte', 40, 'g', 'legumes']],
    steps: ['Cuire patate douce et carotte à l\'eau, écraser en purée.', 'Faire revenir oignon et bœuf.',
      'Monter en couches dans un plat, parsemer d\'emmental.', 'Gratiner 20 min à 200 °C. Servir avec la salade.'],
  }),
  R('veloute-butternut', 'Velouté de butternut & pois chiches grillés', {
    tags: ['vegan'], main: 'legumineuses', time: 40, kcal: 420, keeps: 4, freezable: true,
    ing: [['courge butternut', 300, 'g', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['lait de coco', 30, 'ml', 'epicerie'],
      ['pois chiches cuits', 60, 'g', 'feculents'], ['pain complet', 50, 'g', 'feculents'],
      ['bouillon de légumes (cube)', 0.25, '', 'placard'], ['paprika', 0.5, 'c.à.c', 'placard']],
    steps: ['Cuire butternut et oignon dans le bouillon 25 min.', 'Mixer avec le lait de coco.',
      'Griller les pois chiches au paprika à la poêle.', 'Servir avec le pain.'],
  }),
  R('orzotto-champignons', 'Orzotto (orge) aux champignons & épinards', {
    tags: ['vegetarien'], main: 'cereales', time: 40, kcal: 480, keeps: 3, freezable: false,
    ing: [['orge perlé', 70, 'g', 'feculents'], ['champignons de Paris', 120, 'g', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['parmesan', 15, 'g', 'cremerie'], ['épinards frais', 40, 'g', 'legumes'], ['bouillon de légumes (cube)', 0.25, '', 'placard']],
    steps: ['Faire revenir oignon et champignons.', 'Ajouter l\'orge puis le bouillon petit à petit, 30 min.',
      'Incorporer épinards et parmesan.'],
  }),
  R('fajitas-poulet', 'Fajitas de poulet, poivrons & yaourt', {
    tags: ['viande'], main: 'poulet', time: 25, kcal: 560, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['poivron', 1, '', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['tortillas complètes', 2, '', 'feculents'], ['yaourt grec', 30, 'g', 'cremerie'], ['salade verte', 30, 'g', 'legumes'],
      ['paprika', 1, 'c.à.c', 'placard'], ['cumin', 0.5, 'c.à.c', 'placard']],
    steps: ['Émincer poulet, poivron et oignon.', 'Sauter le tout avec les épices 10 min.', 'Garnir les tortillas au moment de manger.'],
  }),
  R('colin-pane-avoine', 'Colin pané aux flocons d\'avoine, purée de brocoli', {
    tags: ['poisson'], main: 'poisson-blanc', time: 35, kcal: 450, keeps: 2, freezable: true,
    ing: [['filet de colin', 140, 'g', 'proteines'], ['flocons d\'avoine', 20, 'g', 'feculents'], ['œufs', 0.25, '', 'cremerie'],
      ['brocoli', 150, 'g', 'legumes'], ['pommes de terre', 100, 'g', 'feculents'], ['huile d\'olive', 0.5, 'c.à.s', 'placard']],
    steps: ['Passer le colin dans l\'œuf battu puis les flocons.', 'Cuire 15 min à 200 °C sur une plaque huilée.',
      'Cuire brocoli et pommes de terre, mixer en purée.'],
  }),
  R('tajine-legumes', 'Tajine de légumes, pois chiches & semoule complète', {
    tags: ['vegan'], main: 'legumineuses', time: 45, kcal: 500, keeps: 5, freezable: true,
    ing: [['carotte', 1, '', 'legumes'], ['courgette', 0.5, '', 'legumes'], ['navet', 0.5, '', 'legumes'],
      ['pois chiches cuits', 100, 'g', 'feculents'], ['raisins secs', 10, 'g', 'epicerie'], ['semoule complète', 60, 'g', 'feculents'],
      ['oignon', 0.5, '', 'legumes'], ['ras el hanout', 1, 'c.à.c', 'placard']],
    steps: ['Faire revenir l\'oignon avec le ras el hanout.', 'Ajouter les légumes en gros morceaux et 200 ml d\'eau par portion ; mijoter 30 min.',
      'Ajouter pois chiches et raisins 5 min.', 'Préparer la semoule.'],
  }),
  R('poulet-basquaise', 'Poulet basquaise & riz', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 45, kcal: 530, keeps: 4, freezable: true,
    ing: [['blanc de poulet', 130, 'g', 'proteines'], ['poivron', 1, '', 'legumes'], ['tomates concassées', 150, 'g', 'epicerie'],
      ['oignon', 0.5, '', 'legumes'], ['ail', 1, 'gousse', 'legumes'], ['riz basmati', 60, 'g', 'feculents'],
      ['huile d\'olive', 0.5, 'c.à.s', 'placard'], ['paprika', 0.5, 'c.à.c', 'placard']],
    steps: ['Dorer le poulet en morceaux, réserver.', 'Faire revenir oignon, ail et poivrons en lanières.',
      'Ajouter tomates, paprika et poulet ; mijoter 25 min.', 'Cuire le riz.'],
  }),
  R('frittata-epinards', 'Frittata épinards-feta & salade', {
    tags: ['vegetarien', 'sans-gluten'], main: 'oeuf', time: 25, kcal: 390, keeps: 3, freezable: false,
    ing: [['œufs', 2, '', 'cremerie'], ['épinards frais', 80, 'g', 'legumes'], ['feta', 30, 'g', 'cremerie'],
      ['oignon', 0.3, '', 'legumes'], ['salade verte', 40, 'g', 'legumes'], ['pommes de terre', 100, 'g', 'feculents']],
    steps: ['Cuire les pommes de terre en rondelles à la poêle.', 'Ajouter oignon et épinards jusqu\'à ce qu\'ils tombent.',
      'Verser les œufs battus et la feta, cuire à couvert 10 min.', 'Servir tiède ou froide avec la salade.'],
  }),
  R('boeuf-brocoli', 'Bœuf sauté au brocoli & nouilles de riz', {
    tags: ['viande'], main: 'boeuf', time: 25, kcal: 540, keeps: 3, freezable: false,
    ing: [['rumsteck', 110, 'g', 'proteines'], ['brocoli', 150, 'g', 'legumes'], ['nouilles de riz', 60, 'g', 'feculents'],
      ['gingembre frais', 5, 'g', 'legumes'], ['ail', 1, 'gousse', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'],
      ['huile de sésame', 0.5, 'c.à.s', 'placard']],
    steps: ['Trancher finement le bœuf.', 'Saisir 2 min à feu très vif, réserver.', 'Sauter brocoli, ail et gingembre 5 min.',
      'Remettre le bœuf, ajouter la sauce soja et les nouilles cuites.'],
  }),
  R('lentilles-oeuf', 'Lentilles vertes mijotées aux légumes & œuf mollet', {
    inDish: ['lentilles vertes'], tags: ['vegetarien', 'sans-gluten'], main: 'legumineuses', time: 40, kcal: 460, keeps: 5, freezable: true,
    ing: [['lentilles vertes', 70, 'g', 'feculents'], ['carotte', 1, '', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['œufs', 1, '', 'cremerie'], ['moutarde', 0.5, 'c.à.c', 'placard'], ['thym', 0.5, 'c.à.c', 'placard']],
    steps: ['Faire revenir oignon et carotte en dés.', 'Ajouter lentilles, thym et 3 fois leur volume d\'eau ; cuire 25 min.',
      'Lier avec la moutarde.', 'Œuf mollet (6 min) au moment de servir.'],
  }),
  R('saumon-teriyaki', 'Saumon façon teriyaki, riz & bok choy', {
    tags: ['poisson'], main: 'saumon', time: 25, kcal: 560, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 130, 'g', 'proteines'], ['riz basmati', 60, 'g', 'feculents'], ['bok choy', 1, '', 'legumes'],
      ['sauce soja', 1, 'c.à.s', 'placard'], ['miel', 0.5, 'c.à.c', 'placard'], ['gingembre frais', 5, 'g', 'legumes'],
      ['graines de sésame', 5, 'g', 'epicerie']],
    steps: ['Cuire le riz.', 'Mélanger soja, miel et gingembre râpé.', 'Cuire le saumon à la poêle 8 min, napper de sauce.',
      'Sauter le bok choy 3 min.'],
  }),
];

export const SEED_RECIPES = [...BASE_RECIPES, ...EXTRA_RECIPES];
