// Recettes supplémentaires — lot 2a : viande & poisson (quantités POUR 1 PORTION).

const R = (id, name, o) => {
  const { ing, ...rest } = o;
  return { id: 's-' + id, name, ...rest, ingredients: ing.map(([n, qty, unit, cat]) => ({ name: n, qty, unit, cat })) };
};
const HUILE = ['huile d\'olive', 1, 'c.à.s', 'placard'];

export const EXTRA2A_RECIPES = [
  // ================= VIANDE =================
  R('poulet-yassa', 'Poulet yassa aux oignons & citron, riz', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 60, kcal: 560, keeps: 4, freezable: true,
    ing: [['haut de cuisse de poulet', 140, 'g', 'proteines'], ['oignon', 1, '', 'legumes'], ['citron', 0.5, '', 'legumes'],
      ['moutarde', 1, 'c.à.c', 'placard'], ['riz basmati', 60, 'g', 'feculents'], HUILE],
    steps: ['Mariner le poulet avec citron, moutarde et oignons émincés (30 min mini).', 'Dorer le poulet, réserver.',
      'Fondre les oignons de la marinade 15 min, remettre le poulet et la marinade, mijoter 25 min.', 'Servir avec le riz.'],
  }),
  R('mafe-poulet', 'Mafé de poulet léger, patate douce & riz', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 50, kcal: 600, keeps: 4, freezable: true,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['beurre de cacahuète', 15, 'g', 'epicerie'], ['tomates concassées', 100, 'g', 'epicerie'],
      ['carotte', 1, '', 'legumes'], ['patate douce', 80, 'g', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['riz basmati', 50, 'g', 'feculents']],
    steps: ['Dorer poulet et oignon.', 'Ajouter carotte, patate douce, tomates, beurre de cacahuète délayé dans un verre d\'eau.',
      'Mijoter 30 min.', 'Servir avec le riz.'],
  }),
  R('poulet-moutarde-poireaux', 'Poulet à la moutarde, poireaux & riz complet', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 35, kcal: 530, keeps: 3, freezable: true,
    ing: [['blanc de poulet', 130, 'g', 'proteines'], ['poireau', 1, '', 'legumes'], ['moutarde', 1, 'c.à.c', 'placard'],
      ['crème légère 15 %', 30, 'ml', 'cremerie'], ['riz complet', 60, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Dorer le poulet en dés, réserver.', 'Fondre les poireaux 10 min, ajouter crème, moutarde et poulet, 5 min.'],
  }),
  R('poulet-citronnelle', 'Poulet citronnelle-coco, haricots verts & riz', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 30, kcal: 540, keeps: 3, freezable: true,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['lait de coco', 40, 'ml', 'epicerie'], ['citronnelle', 0.5, '', 'legumes'],
      ['haricots verts', 100, 'g', 'legumes'], ['gingembre frais', 5, 'g', 'legumes'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Faire revenir citronnelle hachée et gingembre, ajouter le poulet.', 'Ajouter haricots verts et lait de coco, mijoter 12 min.'],
  }),
  R('souvlaki-bowl', 'Bowl poulet souvlaki, boulgour & tzatziki', {
    tags: ['viande'], main: 'poulet', time: 30, kcal: 560, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['citron', 0.25, '', 'legumes'], ['origan', 0.5, 'c.à.c', 'placard'],
      ['boulgour', 60, 'g', 'feculents'], ['concombre', 0.3, '', 'legumes'], ['yaourt grec', 50, 'g', 'cremerie'],
      ['tomates', 1, '', 'legumes'], ['ail', 1, 'gousse', 'legumes']],
    steps: ['Mariner le poulet avec citron, origan et un filet d\'huile.', 'Cuire le boulgour.', 'Griller le poulet.',
      'Tzatziki : yaourt, concombre râpé et ail. Assembler avec les tomates.'],
  }),
  R('poulet-shawarma', 'Poulet shawarma, chou rouge & pain pita', {
    tags: ['viande'], main: 'poulet', time: 30, kcal: 560, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['cumin', 0.5, 'c.à.c', 'placard'], ['paprika', 0.5, 'c.à.c', 'placard'],
      ['cannelle', 0.25, 'c.à.c', 'placard'], ['pain pita complet', 1, '', 'feculents'], ['chou rouge', 60, 'g', 'legumes'], ['yaourt grec', 30, 'g', 'cremerie']],
    steps: ['Mariner le poulet émincé avec les épices.', 'Le saisir à feu vif 8 min.', 'Émincer le chou.', 'Garnir les pitas au moment de manger.'],
  }),
  R('poulet-cajun', 'Poulet cajun, patate douce & maïs grillé', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 35, kcal: 530, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 130, 'g', 'proteines'], ['épices cajun', 1, 'c.à.c', 'placard'], ['patate douce', 180, 'g', 'legumes'],
      ['maïs en conserve', 40, 'g', 'epicerie'], ['salade verte', 30, 'g', 'legumes'], HUILE],
    steps: ['Rôtir la patate douce en cubes 25 min à 200 °C.', 'Frotter le poulet aux épices, l\'ajouter sur la plaque 15 min.',
      'Griller le maïs à la poêle.', 'Servir avec la salade.'],
  }),
  R('poulet-olives-polenta', 'Poulet tomates-olives & polenta', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 35, kcal: 520, keeps: 4, freezable: true,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['tomates concassées', 120, 'g', 'epicerie'], ['olives noires', 15, 'g', 'epicerie'],
      ['ail', 1, 'gousse', 'legumes'], ['polenta', 50, 'g', 'feculents'], ['herbes de Provence', 0.5, 'c.à.c', 'placard']],
    steps: ['Dorer le poulet et l\'ail.', 'Ajouter tomates, olives et herbes ; mijoter 20 min.', 'Cuire la polenta selon le paquet.'],
  }),
  R('soupe-poulet-vermicelles', 'Soupe de poulet aux légumes & vermicelles', {
    tags: ['viande'], main: 'poulet', time: 40, kcal: 360, keeps: 4, freezable: true,
    ing: [['blanc de poulet', 90, 'g', 'proteines'], ['carotte', 1, '', 'legumes'], ['poireau', 0.3, '', 'legumes'],
      ['céleri branche', 0.3, '', 'legumes'], ['vermicelles', 30, 'g', 'feculents'], ['bouillon de volaille (cube)', 0.5, '', 'placard']],
    steps: ['Cuire légumes et poulet dans le bouillon (400 ml par portion) 25 min.', 'Effilocher le poulet.',
      'Conserver les vermicelles à part ; les cuire 3 min dans la soupe au réchauffage.'],
  }),
  R('poulet-butternut-four', 'Poulet rôti, butternut & pois chiches au four', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 45, kcal: 590, keeps: 4, freezable: false,
    ing: [['haut de cuisse de poulet', 140, 'g', 'proteines'], ['courge butternut', 200, 'g', 'legumes'], ['pois chiches cuits', 60, 'g', 'feculents'],
      ['oignon rouge', 0.5, '', 'legumes'], ['paprika', 1, 'c.à.c', 'placard'], HUILE],
    steps: ['Mélanger butternut en cubes, pois chiches, oignon, paprika et huile sur une plaque.', 'Poser le poulet dessus.', 'Rôtir 40 min à 200 °C.'],
  }),
  R('dinde-curry-vert', 'Dinde au curry vert, courgettes & riz', {
    tags: ['viande', 'sans-gluten'], main: 'dinde', time: 30, kcal: 500, keeps: 3, freezable: true,
    ing: [['escalope de dinde', 120, 'g', 'proteines'], ['pâte de curry', 1, 'c.à.c', 'epicerie'], ['lait de coco', 40, 'ml', 'epicerie'],
      ['courgette', 1, '', 'legumes'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Faire revenir la pâte de curry, ajouter la dinde émincée.', 'Ajouter courgette et lait de coco, mijoter 10 min.'],
  }),
  R('wok-dinde-cajou', 'Wok de dinde, brocoli & noix de cajou', {
    tags: ['viande'], main: 'dinde', time: 25, kcal: 540, keeps: 3, freezable: false,
    ing: [['escalope de dinde', 120, 'g', 'proteines'], ['brocoli', 120, 'g', 'legumes'], ['noix de cajou', 10, 'g', 'epicerie'],
      ['nouilles de riz', 60, 'g', 'feculents'], ['sauce soja', 1, 'c.à.s', 'placard'], ['gingembre frais', 5, 'g', 'legumes']],
    steps: ['Cuire les nouilles.', 'Saisir la dinde émincée, ajouter brocoli et gingembre 5 min.', 'Ajouter nouilles, soja et noix de cajou.'],
  }),
  R('blanquette-dinde', 'Blanquette de dinde légère & riz', {
    tags: ['viande', 'sans-gluten'], main: 'dinde', time: 45, kcal: 520, keeps: 4, freezable: true,
    ing: [['escalope de dinde', 130, 'g', 'proteines'], ['carotte', 1, '', 'legumes'], ['champignons de Paris', 80, 'g', 'legumes'],
      ['oignon', 0.5, '', 'legumes'], ['crème légère 15 %', 30, 'ml', 'cremerie'], ['bouillon de volaille (cube)', 0.25, '', 'placard'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Pocher dinde, carotte et oignon dans le bouillon 25 min.', 'Ajouter les champignons 10 min.', 'Lier avec la crème hors du feu.', 'Servir avec le riz.'],
  }),
  R('boulettes-dinde-citron', 'Boulettes de dinde, sauce yaourt-citron & quinoa', {
    tags: ['viande'], main: 'dinde', time: 35, kcal: 530, keeps: 3, freezable: true,
    ing: [['dinde hachée', 120, 'g', 'proteines'], ['flocons d\'avoine', 15, 'g', 'feculents'], ['œufs', 0.25, '', 'cremerie'],
      ['persil frais', 0.1, 'botte', 'legumes'], ['quinoa', 60, 'g', 'feculents'], ['yaourt grec', 40, 'g', 'cremerie'], ['citron', 0.25, '', 'legumes']],
    steps: ['Mélanger dinde, avoine, œuf et persil ; former des boulettes.', 'Cuire 18 min à 200 °C.', 'Cuire le quinoa.', 'Sauce : yaourt et citron.'],
  }),
  R('goulash', 'Goulash de bœuf léger & pommes de terre', {
    tags: ['viande', 'sans-gluten'], main: 'boeuf', time: 120, kcal: 540, keeps: 5, freezable: true,
    ing: [['bœuf à braiser (paleron)', 110, 'g', 'proteines'], ['poivron', 0.5, '', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['tomates concassées', 100, 'g', 'epicerie'], ['paprika', 1, 'c.à.c', 'placard'], ['pommes de terre', 150, 'g', 'feculents']],
    steps: ['Saisir le bœuf en cubes avec oignon et paprika.', 'Ajouter poivron, tomates et un verre d\'eau ; mijoter 1 h 30.',
      'Ajouter les pommes de terre en cubes les 25 dernières minutes.'],
  }),
  R('bibimbap', 'Bibimbap bœuf, légumes & œuf', {
    tags: ['viande'], main: 'boeuf', time: 35, kcal: 600, keeps: 3, freezable: false,
    ing: [['bœuf haché 5 %', 90, 'g', 'proteines'], ['riz basmati', 60, 'g', 'feculents'], ['carotte', 0.5, '', 'legumes'],
      ['épinards frais', 50, 'g', 'legumes'], ['courgette', 0.5, '', 'legumes'], ['œufs', 1, '', 'cremerie'], ['sauce soja', 1, 'c.à.s', 'placard']],
    steps: ['Cuire le riz.', 'Sauter séparément carotte, courgette et épinards.', 'Cuire le bœuf avec la sauce soja.',
      'Œuf au plat au moment de servir, sur le bol assemblé.'],
  }),
  R('daube-provencale', 'Daube provençale légère & pâtes complètes', {
    tags: ['viande'], main: 'boeuf', time: 150, kcal: 580, keeps: 5, freezable: true,
    ing: [['bœuf à braiser (paleron)', 110, 'g', 'proteines'], ['carotte', 1, '', 'legumes'], ['tomates concassées', 100, 'g', 'epicerie'],
      ['olives noires', 10, 'g', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['herbes de Provence', 0.5, 'c.à.c', 'placard'], ['pâtes complètes', 60, 'g', 'feculents']],
    steps: ['Saisir le bœuf, ajouter oignon et carottes.', 'Ajouter tomates, herbes et un verre d\'eau ; mijoter 2 h à couvert.',
      'Ajouter les olives 10 min avant la fin.', 'Cuire les pâtes.'],
  }),
  R('salade-thai-boeuf', 'Salade thaï au bœuf, herbes fraîches & riz', {
    tags: ['viande'], main: 'boeuf', time: 25, kcal: 450, keeps: 2, freezable: false,
    ing: [['rumsteck', 100, 'g', 'proteines'], ['concombre', 0.3, '', 'legumes'], ['oignon rouge', 0.3, '', 'legumes'],
      ['menthe fraîche', 0.1, 'botte', 'legumes'], ['coriandre fraîche', 0.1, 'botte', 'legumes'], ['citron vert', 0.5, '', 'legumes'],
      ['sauce soja', 1, 'c.à.s', 'placard'], ['riz basmati', 50, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Saisir le bœuf 2 min par face, trancher finement.', 'Mélanger avec concombre, oignon et herbes.',
      'Assaisonner citron vert-soja au moment de servir.'],
  }),
  R('boulettes-boeuf-courgettes', 'Boulettes de bœuf, courgettes à la tomate & semoule', {
    tags: ['viande'], main: 'boeuf', time: 40, kcal: 560, keeps: 4, freezable: true,
    ing: [['bœuf haché 5 %', 100, 'g', 'proteines'], ['oignon', 0.3, '', 'legumes'], ['courgette', 1, '', 'legumes'],
      ['coulis de tomate', 120, 'g', 'epicerie'], ['semoule complète', 60, 'g', 'feculents'], ['cumin', 0.5, 'c.à.c', 'placard']],
    steps: ['Former des boulettes avec bœuf, oignon râpé et cumin, les dorer.', 'Ajouter courgette en dés et coulis, mijoter 20 min.', 'Préparer la semoule.'],
  }),
  R('chou-farci', 'Chou farci léger au bœuf', {
    inDish: ['riz complet'], tags: ['viande', 'sans-gluten'], main: 'boeuf', time: 80, kcal: 450, keeps: 4, freezable: true,
    ing: [['chou vert', 0.2, '', 'legumes'], ['bœuf haché 5 %', 90, 'g', 'proteines'], ['riz complet', 30, 'g', 'feculents'],
      ['oignon', 0.3, '', 'legumes'], ['tomates concassées', 100, 'g', 'epicerie']],
    steps: ['Blanchir les feuilles de chou 5 min.', 'Mélanger bœuf, riz cru et oignon haché.', 'Farcir et rouler les feuilles, les serrer dans un plat.',
      'Couvrir de tomates, cuire 1 h à 180 °C.'],
  }),
  R('colombo-porc', 'Colombo de porc & riz', {
    tags: ['viande', 'sans-gluten'], main: 'porc', time: 50, kcal: 560, keeps: 4, freezable: true,
    ing: [['filet mignon de porc', 120, 'g', 'proteines'], ['colombo (épices)', 1, 'c.à.c', 'placard'], ['courgette', 0.5, '', 'legumes'],
      ['pommes de terre', 100, 'g', 'feculents'], ['lait de coco', 30, 'ml', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['riz basmati', 50, 'g', 'feculents']],
    steps: ['Dorer porc et oignon avec le colombo.', 'Ajouter pommes de terre, courgette, lait de coco et un verre d\'eau ; 30 min.', 'Servir avec le riz.'],
  }),
  R('porc-pommes-celeri', 'Filet mignon aux pommes & purée de céleri', {
    tags: ['viande', 'sans-gluten'], main: 'porc', time: 45, kcal: 470, keeps: 3, freezable: true,
    ing: [['filet mignon de porc', 120, 'g', 'proteines'], ['pomme', 1, '', 'legumes'], ['céleri-rave', 200, 'g', 'legumes'],
      ['lait demi-écrémé', 30, 'ml', 'cremerie'], ['thym', 0.5, 'c.à.c', 'placard']],
    steps: ['Cuire le céleri en cubes 20 min à l\'eau, mixer avec le lait.', 'Saisir le filet mignon puis le cuire 20 min à 180 °C avec les pommes en quartiers et le thym.'],
  }),
  R('tacos-porc', 'Tacos de porc effiloché, chou & citron vert', {
    tags: ['viande'], main: 'porc', time: 40, kcal: 560, keeps: 3, freezable: true,
    ing: [['filet mignon de porc', 110, 'g', 'proteines'], ['tortillas complètes', 2, '', 'feculents'], ['chou rouge', 60, 'g', 'legumes'],
      ['paprika fumé', 1, 'c.à.c', 'placard'], ['citron vert', 0.25, '', 'legumes'], ['yaourt grec', 30, 'g', 'cremerie']],
    steps: ['Cuire le porc au paprika à couvert 30 min avec un fond d\'eau, l\'effilocher.', 'Émincer le chou.', 'Garnir les tortillas au moment de manger.'],
  }),
  R('yakisoba-porc', 'Nouilles sautées au porc & chou (yakisoba)', {
    tags: ['viande'], main: 'porc', time: 25, kcal: 560, keeps: 3, freezable: false,
    ing: [['filet mignon de porc', 100, 'g', 'proteines'], ['nouilles aux œufs', 70, 'g', 'feculents'], ['chou vert', 0.15, '', 'legumes'],
      ['carotte', 0.5, '', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'], ['oignon nouveau', 0.5, '', 'legumes']],
    steps: ['Cuire les nouilles.', 'Saisir le porc émincé.', 'Sauter chou et carotte émincés 5 min.', 'Ajouter nouilles et soja. Oignon nouveau au service.'],
  }),
  R('gratin-pates-jambon', 'Gratin de pâtes complètes, jambon & brocoli', {
    tags: ['viande'], main: 'porc', time: 40, kcal: 540, keeps: 4, freezable: true,
    ing: [['pâtes complètes', 60, 'g', 'feculents'], ['jambon blanc', 1, 'tranche', 'proteines'], ['brocoli', 120, 'g', 'legumes'],
      ['lait demi-écrémé', 100, 'ml', 'cremerie'], ['farine', 8, 'g', 'epicerie'], ['emmental râpé', 20, 'g', 'cremerie']],
    steps: ['Cuire pâtes et brocoli (brocoli les 4 dernières minutes).', 'Préparer une béchamel légère.',
      'Mélanger avec le jambon en dés, parsemer d\'emmental.', 'Gratiner 20 min à 200 °C.'],
  }),
  R('saute-veau', 'Sauté de veau aux carottes & riz', {
    tags: ['viande', 'sans-gluten'], main: 'veau', time: 80, kcal: 500, keeps: 4, freezable: true,
    ing: [['sauté de veau', 120, 'g', 'proteines'], ['carotte', 1, '', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['tomates concassées', 80, 'g', 'epicerie'], ['thym', 0.5, 'c.à.c', 'placard'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Dorer le veau et l\'oignon.', 'Ajouter carottes, tomates, thym et un verre d\'eau ; mijoter 1 h.', 'Servir avec le riz.'],
  }),
  R('tajine-agneau', 'Tajine d\'agneau, pois chiches & pruneaux', {
    tags: ['viande'], main: 'agneau', time: 90, kcal: 600, keeps: 5, freezable: true,
    ing: [['gigot d\'agneau', 100, 'g', 'proteines'], ['pois chiches cuits', 60, 'g', 'feculents'], ['courgette', 0.5, '', 'legumes'],
      ['pruneaux', 15, 'g', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['ras el hanout', 1, 'c.à.c', 'placard'], ['semoule complète', 50, 'g', 'feculents']],
    steps: ['Dorer l\'agneau en cubes avec l\'oignon et les épices.', 'Couvrir d\'eau, mijoter 1 h.',
      'Ajouter courgette, pois chiches et pruneaux 15 min.', 'Préparer la semoule.'],
  }),
  R('poulet-tandoori', 'Poulet tandoori, chou-fleur rôti & riz', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 40, kcal: 500, keeps: 3, freezable: true,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['yaourt grec', 30, 'g', 'cremerie'], ['épices tandoori', 1, 'c.à.c', 'placard'],
      ['chou-fleur', 0.25, '', 'legumes'], ['riz basmati', 50, 'g', 'feculents'], HUILE],
    steps: ['Mariner le poulet dans yaourt et épices.', 'Rôtir chou-fleur et poulet 25 min à 210 °C.', 'Cuire le riz.'],
  }),
  R('gratin-courgette-poulet', 'Gratin de courgettes au poulet & feta', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 45, kcal: 430, keeps: 3, freezable: true,
    ing: [['blanc de poulet', 110, 'g', 'proteines'], ['courgette', 1.5, '', 'legumes'], ['œufs', 1, '', 'cremerie'],
      ['feta', 25, 'g', 'cremerie'], ['lait demi-écrémé', 40, 'ml', 'cremerie'], ['salade verte', 30, 'g', 'legumes']],
    steps: ['Faire revenir les courgettes en rondelles et le poulet en dés.', 'Battre œufs et lait, verser dessus, émietter la feta.',
      'Cuire 25 min à 190 °C. Servir avec la salade.'],
  }),
  R('ramen-poulet', 'Ramen au poulet, champignons & œuf mollet', {
    tags: ['viande'], main: 'poulet', time: 40, kcal: 520, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 100, 'g', 'proteines'], ['nouilles ramen', 60, 'g', 'feculents'], ['bouillon de volaille (cube)', 0.5, '', 'placard'],
      ['champignons de Paris', 60, 'g', 'legumes'], ['bok choy', 0.5, '', 'legumes'], ['œufs', 1, '', 'cremerie'],
      ['sauce soja', 1, 'c.à.s', 'placard'], ['gingembre frais', 5, 'g', 'legumes']],
    steps: ['Infuser bouillon, gingembre et soja 10 min ; y pocher poulet et champignons.', 'Œufs mollets 6 min 30, écaler.',
      'Garder nouilles et bouillon séparés.', 'Au service : nouilles, bok choy, bouillon chaud, œuf.'],
  }),
  R('chili-blanc-dinde', 'Chili blanc à la dinde & haricots blancs', {
    tags: ['viande', 'sans-gluten'], main: 'dinde', time: 40, kcal: 470, keeps: 5, freezable: true,
    ing: [['dinde hachée', 100, 'g', 'proteines'], ['haricots blancs cuits', 100, 'g', 'feculents'], ['maïs en conserve', 30, 'g', 'epicerie'],
      ['poivron', 0.5, '', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['cumin', 1, 'c.à.c', 'placard'],
      ['bouillon de volaille (cube)', 0.25, '', 'placard'], ['yaourt grec', 20, 'g', 'cremerie']],
    steps: ['Dorer dinde, oignon et poivron avec le cumin.', 'Ajouter haricots, maïs et bouillon (200 ml par portion), mijoter 20 min.',
      'Écraser une partie des haricots pour épaissir.', 'Yaourt au service.'],
  }),
  R('salade-soba-poulet', 'Salade de soba au poulet, edamame & sésame', {
    tags: ['viande'], main: 'poulet', time: 25, kcal: 520, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 100, 'g', 'proteines'], ['nouilles soba', 60, 'g', 'feculents'], ['concombre', 0.3, '', 'legumes'],
      ['carotte', 0.5, '', 'legumes'], ['edamame surgelés', 40, 'g', 'surgeles'], ['sauce soja', 1, 'c.à.s', 'placard'], ['huile de sésame', 0.5, 'c.à.s', 'placard']],
    steps: ['Cuire soba et edamame, rincer à froid.', 'Griller et trancher le poulet.', 'Ajouter concombre et carotte en julienne.', 'Sauce soja-sésame au moment de servir.'],
  }),
  R('picadillo', 'Picadillo de bœuf, haricots noirs & riz', {
    tags: ['viande', 'sans-gluten'], main: 'boeuf', time: 40, kcal: 600, keeps: 4, freezable: true,
    ing: [['bœuf haché 5 %', 100, 'g', 'proteines'], ['poivron', 0.5, '', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['tomates concassées', 80, 'g', 'epicerie'], ['olives vertes', 10, 'g', 'epicerie'], ['raisins secs', 10, 'g', 'epicerie'],
      ['haricots noirs cuits', 50, 'g', 'feculents'], ['riz basmati', 50, 'g', 'feculents'], ['cumin', 0.5, 'c.à.c', 'placard']],
    steps: ['Dorer bœuf, oignon et poivron avec le cumin.', 'Ajouter tomates, olives et raisins, mijoter 20 min.', 'Réchauffer les haricots, cuire le riz.'],
  }),

  // ================= POISSON =================
  R('saumon-moutarde-miel', 'Saumon moutarde-miel, haricots verts & quinoa', {
    tags: ['poisson', 'sans-gluten'], main: 'saumon', time: 25, kcal: 560, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 130, 'g', 'proteines'], ['moutarde', 0.5, 'c.à.c', 'placard'], ['miel', 0.5, 'c.à.c', 'placard'],
      ['haricots verts', 150, 'g', 'legumes'], ['quinoa', 50, 'g', 'feculents']],
    steps: ['Cuire quinoa et haricots verts.', 'Badigeonner le saumon de moutarde-miel.', 'Cuire 12 min à 200 °C.'],
  }),
  R('lasagnes-saumon', 'Lasagnes saumon-épinards', {
    tags: ['poisson'], main: 'saumon', time: 55, kcal: 540, keeps: 3, freezable: true,
    ing: [['plaques de lasagne', 50, 'g', 'feculents'], ['pavé de saumon', 80, 'g', 'proteines'], ['épinards frais', 100, 'g', 'legumes'],
      ['ricotta', 40, 'g', 'cremerie'], ['lait demi-écrémé', 60, 'ml', 'cremerie'], ['emmental râpé', 15, 'g', 'cremerie']],
    steps: ['Faire tomber les épinards, mélanger avec ricotta et lait.', 'Alterner plaques, épinards et saumon en dés.', 'Finir par l\'emmental, cuire 35 min à 180 °C.'],
  }),
  R('croquettes-saumon', 'Croquettes de saumon & patate douce, salade', {
    tags: ['poisson'], main: 'saumon', time: 40, kcal: 470, keeps: 3, freezable: true,
    ing: [['pavé de saumon', 90, 'g', 'proteines'], ['patate douce', 120, 'g', 'legumes'], ['œufs', 0.25, '', 'cremerie'],
      ['flocons d\'avoine', 10, 'g', 'feculents'], ['aneth frais', 0.1, 'botte', 'legumes'], ['salade verte', 40, 'g', 'legumes']],
    steps: ['Cuire la patate douce, l\'écraser.', 'Ajouter saumon cru haché, œuf, avoine et aneth.', 'Former des galettes, cuire 20 min à 200 °C.'],
  }),
  R('curry-vert-saumon', 'Curry vert de saumon & haricots verts, riz', {
    tags: ['poisson', 'sans-gluten'], main: 'saumon', time: 25, kcal: 590, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 110, 'g', 'proteines'], ['lait de coco', 50, 'ml', 'epicerie'], ['pâte de curry', 1, 'c.à.c', 'epicerie'],
      ['haricots verts', 100, 'g', 'legumes'], ['riz basmati', 50, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Faire revenir la pâte de curry, ajouter lait de coco et haricots verts, 8 min.', 'Pocher le saumon en cubes 5 min.'],
  }),
  R('cabillaud-sauce-vierge', 'Cabillaud sauce vierge & écrasé de pommes de terre', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 30, kcal: 450, keeps: 2, freezable: false,
    ing: [['dos de cabillaud', 140, 'g', 'proteines'], ['tomates', 1, '', 'legumes'], ['basilic frais', 0.1, 'botte', 'legumes'],
      ['pommes de terre', 180, 'g', 'feculents'], ['citron', 0.25, '', 'legumes'], HUILE],
    steps: ['Cuire les pommes de terre, écraser à la fourchette avec un filet d\'huile.', 'Sauce vierge : tomates en dés, basilic, citron, huile.',
      'Cuire le cabillaud 12 min à 190 °C.'],
  }),
  R('cabillaud-legumes-boulgour', 'Cabillaud au four, légumes du soleil & boulgour', {
    tags: ['poisson'], main: 'poisson-blanc', time: 35, kcal: 430, keeps: 2, freezable: false,
    ing: [['dos de cabillaud', 130, 'g', 'proteines'], ['courgette', 0.5, '', 'legumes'], ['poivron', 0.5, '', 'legumes'],
      ['tomates', 1, '', 'legumes'], ['boulgour', 50, 'g', 'feculents'], ['herbes de Provence', 0.5, 'c.à.c', 'placard'], HUILE],
    steps: ['Rôtir courgette, poivron et tomates en dés 20 min à 200 °C.', 'Ajouter le cabillaud sur les légumes, 12 min.', 'Cuire le boulgour.'],
  }),
  R('colin-coco-patate', 'Colin au lait de coco & patate douce', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 30, kcal: 450, keeps: 2, freezable: true,
    ing: [['filet de colin', 130, 'g', 'proteines'], ['patate douce', 150, 'g', 'legumes'], ['lait de coco', 40, 'ml', 'epicerie'],
      ['épinards frais', 50, 'g', 'legumes'], ['curry en poudre', 1, 'c.à.c', 'placard'], ['citron vert', 0.25, '', 'legumes']],
    steps: ['Cuire la patate douce en dés avec le curry, le lait de coco et un peu d\'eau, 15 min.', 'Ajouter le colin en morceaux et les épinards, 7 min.', 'Citron vert.'],
  }),
  R('pates-colin-petits-pois', 'Pâtes complètes au colin, citron & petits pois', {
    tags: ['poisson'], main: 'poisson-blanc', time: 25, kcal: 520, keeps: 2, freezable: false,
    ing: [['filet de colin', 110, 'g', 'proteines'], ['pâtes complètes', 70, 'g', 'feculents'], ['petits pois surgelés', 60, 'g', 'surgeles'],
      ['crème légère 15 %', 20, 'ml', 'cremerie'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire les pâtes avec les petits pois.', 'Poêler le colin, l\'émietter.', 'Mélanger avec crème, zeste et jus de citron.'],
  }),
  R('riz-thon-poivrons', 'Riz au thon, tomates & poivrons', {
    inDish: ['riz basmati'], tags: ['poisson', 'sans-gluten'], main: 'thon', time: 35, kcal: 500, keeps: 3, freezable: false,
    ing: [['thon au naturel', 80, 'g', 'epicerie'], ['riz basmati', 60, 'g', 'feculents'], ['poivron', 0.5, '', 'legumes'],
      ['tomates concassées', 100, 'g', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['paprika', 0.5, 'c.à.c', 'placard']],
    steps: ['Faire revenir oignon et poivron.', 'Ajouter le riz, le paprika, les tomates et 1,5 fois le volume du riz en eau ; 18 min.', 'Incorporer le thon émietté.'],
  }),
  R('gratin-courgette-thon', 'Gratin de courgettes au thon', {
    tags: ['poisson', 'sans-gluten'], main: 'thon', time: 40, kcal: 360, keeps: 3, freezable: false,
    ing: [['thon au naturel', 80, 'g', 'epicerie'], ['courgette', 1, '', 'legumes'], ['œufs', 1, '', 'cremerie'],
      ['lait demi-écrémé', 50, 'ml', 'cremerie'], ['emmental râpé', 15, 'g', 'cremerie'], ['pain complet', 40, 'g', 'feculents']],
    steps: ['Faire revenir les courgettes en rondelles.', 'Mélanger avec thon, œufs battus et lait.', 'Parsemer d\'emmental, cuire 25 min à 190 °C. Servir avec le pain.'],
  }),
  R('salade-quinoa-thon', 'Salade quinoa, thon, haricots blancs & roquette', {
    tags: ['poisson', 'sans-gluten'], main: 'thon', time: 20, kcal: 500, keeps: 3, freezable: false,
    ing: [['quinoa', 50, 'g', 'feculents'], ['thon au naturel', 70, 'g', 'epicerie'], ['haricots blancs cuits', 60, 'g', 'feculents'],
      ['roquette', 30, 'g', 'legumes'], ['tomates cerises', 80, 'g', 'legumes'], ['citron', 0.25, '', 'legumes'], HUILE],
    steps: ['Cuire le quinoa, refroidir.', 'Ajouter haricots, tomates et thon.', 'Roquette et assaisonnement au moment de servir.'],
  }),
  R('salade-sardines-pdt', 'Salade tiède pommes de terre, sardines & haricots verts', {
    tags: ['poisson', 'sans-gluten'], main: 'sardines', time: 25, kcal: 480, keeps: 3, freezable: false,
    ing: [['sardines à l\'huile', 70, 'g', 'epicerie'], ['pommes de terre', 150, 'g', 'feculents'], ['haricots verts', 100, 'g', 'legumes'],
      ['échalote', 0.3, '', 'legumes'], ['moutarde', 0.5, 'c.à.c', 'placard'], ['vinaigre de cidre', 1, 'c.à.c', 'placard']],
    steps: ['Cuire pommes de terre et haricots verts.', 'Vinaigrette moutarde-vinaigre-échalote.', 'Ajouter les sardines au moment de servir.'],
  }),
  R('maquereau-poireaux', 'Maquereau rôti à la moutarde, poireaux & quinoa', {
    tags: ['poisson', 'sans-gluten'], main: 'maquereau', time: 30, kcal: 580, keeps: 2, freezable: false,
    ing: [['filet de maquereau', 120, 'g', 'proteines'], ['moutarde', 0.5, 'c.à.c', 'placard'], ['poireau', 0.5, '', 'legumes'],
      ['quinoa', 50, 'g', 'feculents'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire le quinoa.', 'Fondre les poireaux 12 min.', 'Badigeonner le maquereau de moutarde, cuire 10 min à 200 °C.'],
  }),
  R('crevettes-grecque', 'Crevettes à la grecque, tomates, feta & boulgour', {
    tags: ['poisson'], main: 'crevettes', time: 25, kcal: 480, keeps: 2, freezable: false,
    ing: [['crevettes décortiquées', 110, 'g', 'proteines'], ['tomates concassées', 120, 'g', 'epicerie'], ['feta', 25, 'g', 'cremerie'],
      ['ail', 1, 'gousse', 'legumes'], ['origan', 0.5, 'c.à.c', 'placard'], ['boulgour', 60, 'g', 'feculents']],
    steps: ['Cuire le boulgour.', 'Mijoter ail, tomates et origan 10 min.', 'Ajouter crevettes 3 min, émietter la feta.'],
  }),
  R('tom-kha-crevettes', 'Soupe thaï coco aux crevettes (tom kha)', {
    tags: ['poisson', 'sans-gluten'], main: 'crevettes', time: 25, kcal: 410, keeps: 2, freezable: false,
    ing: [['crevettes décortiquées', 90, 'g', 'proteines'], ['lait de coco', 60, 'ml', 'epicerie'], ['champignons de Paris', 60, 'g', 'legumes'],
      ['citronnelle', 0.5, '', 'legumes'], ['citron vert', 0.25, '', 'legumes'], ['gingembre frais', 5, 'g', 'legumes'],
      ['nouilles de riz', 40, 'g', 'feculents'], ['bouillon de légumes (cube)', 0.25, '', 'placard']],
    steps: ['Infuser citronnelle et gingembre 10 min dans le bouillon et le lait de coco (300 ml par portion).', 'Ajouter champignons 5 min, puis crevettes 3 min.',
      'Nouilles à part. Citron vert au service.'],
  }),
  R('bowl-crevettes-mangue', 'Bowl crevettes, mangue & quinoa', {
    tags: ['poisson', 'sans-gluten'], main: 'crevettes', time: 20, kcal: 480, keeps: 2, freezable: false,
    ing: [['crevettes décortiquées', 100, 'g', 'proteines'], ['mangue', 0.3, '', 'legumes'], ['quinoa', 50, 'g', 'feculents'],
      ['concombre', 0.3, '', 'legumes'], ['avocat', 0.3, '', 'legumes'], ['citron vert', 0.25, '', 'legumes']],
    steps: ['Cuire le quinoa.', 'Saisir les crevettes 3 min.', 'Couper mangue et concombre.', 'Avocat et citron vert au moment de manger.'],
  }),
  R('courgettes-spaghetti-crevettes', 'Spaghetti de courgettes aux crevettes & ail', {
    tags: ['poisson'], main: 'crevettes', time: 15, kcal: 340, keeps: 2, freezable: false,
    ing: [['courgette', 2, '', 'legumes'], ['crevettes décortiquées', 110, 'g', 'proteines'], ['ail', 1, 'gousse', 'legumes'],
      ['tomates cerises', 80, 'g', 'legumes'], ['parmesan', 10, 'g', 'cremerie'], ['pain complet', 40, 'g', 'feculents']],
    steps: ['Tailler les courgettes en spaghetti (ou tagliatelles à l\'économe).', 'Sauter ail et crevettes 3 min.',
      'Ajouter courgettes et tomates 2 min seulement. Parmesan au service.'],
  }),
  R('gratin-truite', 'Gratin de pommes de terre à la truite & poireaux', {
    tags: ['poisson', 'sans-gluten'], main: 'truite', time: 50, kcal: 500, keeps: 3, freezable: true,
    ing: [['filet de truite', 100, 'g', 'proteines'], ['pommes de terre', 180, 'g', 'feculents'], ['poireau', 0.5, '', 'legumes'],
      ['lait demi-écrémé', 80, 'ml', 'cremerie'], ['emmental râpé', 15, 'g', 'cremerie']],
    steps: ['Fondre les poireaux.', 'Alterner pommes de terre en fines rondelles, poireaux et truite en morceaux.', 'Verser le lait, parsemer d\'emmental, cuire 40 min à 180 °C.'],
  }),
  R('merlu-basquaise', 'Merlu basquaise & riz', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 35, kcal: 430, keeps: 2, freezable: true,
    ing: [['filet de merlu', 130, 'g', 'proteines'], ['poivron', 1, '', 'legumes'], ['tomates concassées', 120, 'g', 'epicerie'],
      ['oignon', 0.5, '', 'legumes'], ['paprika', 0.5, 'c.à.c', 'placard'], ['riz basmati', 50, 'g', 'feculents']],
    steps: ['Mijoter oignon, poivrons, tomates et paprika 20 min.', 'Déposer le merlu, couvrir 8 min.', 'Cuire le riz.'],
  }),
  R('fish-chips-four', 'Fish & chips au four, frites de patate douce & petits pois', {
    tags: ['poisson'], main: 'poisson-blanc', time: 40, kcal: 520, keeps: 2, freezable: false,
    ing: [['filet de colin', 130, 'g', 'proteines'], ['flocons d\'avoine', 15, 'g', 'feculents'], ['œufs', 0.25, '', 'cremerie'],
      ['patate douce', 180, 'g', 'legumes'], ['petits pois surgelés', 60, 'g', 'surgeles'], HUILE],
    steps: ['Frites de patate douce : 30 min à 210 °C.', 'Paner le colin (œuf puis avoine), l\'ajouter les 15 dernières minutes.', 'Cuire les petits pois, les écraser grossièrement.'],
  }),
  R('saumon-sesame-soba', 'Saumon en croûte de sésame, soba & brocoli', {
    tags: ['poisson'], main: 'saumon', time: 25, kcal: 600, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 120, 'g', 'proteines'], ['graines de sésame', 10, 'g', 'epicerie'], ['nouilles soba', 60, 'g', 'feculents'],
      ['brocoli', 120, 'g', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard']],
    steps: ['Cuire soba et brocoli.', 'Badigeonner le saumon de soja, le rouler dans le sésame.', 'Cuire 12 min à 200 °C.'],
  }),
  R('cabillaud-dahl', 'Cabillaud sur dahl de lentilles corail', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 35, kcal: 500, keeps: 2, freezable: false,
    ing: [['dos de cabillaud', 110, 'g', 'proteines'], ['lentilles corail', 50, 'g', 'feculents'], ['lait de coco', 30, 'ml', 'epicerie'],
      ['tomates concassées', 80, 'g', 'epicerie'], ['épinards frais', 40, 'g', 'legumes'], ['curry en poudre', 1, 'c.à.c', 'placard']],
    steps: ['Cuire lentilles, tomates, lait de coco et curry 20 min.', 'Ajouter les épinards.', 'Cuire le cabillaud 10 min à 190 °C, le poser sur le dahl.'],
  }),
  R('salade-riz-thon', 'Salade de riz complet, thon, maïs & poivron', {
    tags: ['poisson', 'sans-gluten'], main: 'thon', time: 30, kcal: 510, keeps: 3, freezable: false,
    ing: [['riz complet', 50, 'g', 'feculents'], ['thon au naturel', 70, 'g', 'epicerie'], ['maïs en conserve', 40, 'g', 'epicerie'],
      ['poivron', 0.5, '', 'legumes'], ['tomates cerises', 60, 'g', 'legumes'], HUILE],
    steps: ['Cuire le riz, refroidir.', 'Ajouter poivron en dés, maïs, tomates et thon.', 'Huile au moment de servir.'],
  }),
  R('colin-moutarde-poireaux', 'Colin à la moutarde, poireaux & pommes vapeur', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 35, kcal: 450, keeps: 2, freezable: false,
    ing: [['filet de colin', 130, 'g', 'proteines'], ['moutarde', 1, 'c.à.c', 'placard'], ['poireau', 1, '', 'legumes'],
      ['crème légère 15 %', 20, 'ml', 'cremerie'], ['pommes de terre', 150, 'g', 'feculents']],
    steps: ['Cuire les pommes de terre à la vapeur.', 'Fondre les poireaux, ajouter crème et moutarde.', 'Déposer le colin dessus, couvrir 8 min.'],
  }),
  R('pates-saumon-epinards', 'Pâtes complètes au saumon & épinards', {
    tags: ['poisson'], main: 'saumon', time: 20, kcal: 580, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 90, 'g', 'proteines'], ['pâtes complètes', 70, 'g', 'feculents'], ['épinards frais', 80, 'g', 'legumes'],
      ['crème légère 15 %', 30, 'ml', 'cremerie'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire les pâtes.', 'Poêler le saumon en dés 4 min.', 'Ajouter épinards et crème, puis pâtes et zeste de citron.'],
  }),
  R('curry-crevettes-ananas', 'Curry de crevettes à l\'ananas & riz', {
    tags: ['poisson', 'sans-gluten'], main: 'crevettes', time: 25, kcal: 480, keeps: 2, freezable: false,
    ing: [['crevettes décortiquées', 100, 'g', 'proteines'], ['ananas', 80, 'g', 'legumes'], ['lait de coco', 40, 'ml', 'epicerie'],
      ['poivron', 0.5, '', 'legumes'], ['curry en poudre', 1, 'c.à.c', 'placard'], ['riz basmati', 50, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Sauter poivron et curry, ajouter lait de coco et ananas, 8 min.', 'Ajouter les crevettes 3 min.'],
  }),
  R('bowl-sardines', 'Bowl sardines, quinoa & légumes croquants', {
    tags: ['poisson', 'sans-gluten'], main: 'sardines', time: 20, kcal: 500, keeps: 2, freezable: false,
    ing: [['sardines à l\'huile', 70, 'g', 'epicerie'], ['quinoa', 50, 'g', 'feculents'], ['carotte', 0.5, '', 'legumes'],
      ['concombre', 0.3, '', 'legumes'], ['radis', 4, '', 'legumes'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire le quinoa.', 'Râper la carotte, trancher concombre et radis.', 'Sardines et citron au moment de servir.'],
  }),
  R('merlu-fenouil-orange', 'Merlu en papillote, fenouil & orange, riz complet', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 35, kcal: 400, keeps: 2, freezable: false,
    ing: [['filet de merlu', 140, 'g', 'proteines'], ['fenouil', 0.5, '', 'legumes'], ['orange', 0.25, '', 'legumes'], ['riz complet', 50, 'g', 'feculents'], HUILE],
    steps: ['Cuire le riz.', 'Émincer finement le fenouil, le poser sur du papier cuisson avec le merlu.', 'Ajouter jus d\'orange et huile, fermer, cuire 20 min à 200 °C.'],
  }),
  R('soupe-poisson-express', 'Soupe de poisson express, fenouil & pommes de terre', {
    tags: ['poisson'], main: 'poisson-blanc', time: 40, kcal: 380, keeps: 2, freezable: true,
    ing: [['dos de cabillaud', 110, 'g', 'proteines'], ['fenouil', 0.3, '', 'legumes'], ['tomates concassées', 150, 'g', 'epicerie'],
      ['pommes de terre', 100, 'g', 'feculents'], ['oignon', 0.3, '', 'legumes'], ['pain complet', 40, 'g', 'feculents']],
    steps: ['Faire revenir oignon et fenouil.', 'Ajouter tomates, pommes de terre en dés et 300 ml d\'eau par portion ; 20 min.', 'Ajouter le cabillaud en morceaux 6 min.'],
  }),
  R('saumon-pesto-orzo', 'Saumon au pesto, tomates cerises & orzo', {
    tags: ['poisson'], main: 'saumon', time: 25, kcal: 590, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 120, 'g', 'proteines'], ['pesto', 15, 'g', 'epicerie'], ['tomates cerises', 100, 'g', 'legumes'],
      ['pâtes orzo', 60, 'g', 'feculents'], ['roquette', 20, 'g', 'legumes']],
    steps: ['Cuire l\'orzo.', 'Napper le saumon de pesto, le cuire 12 min à 200 °C avec les tomates.', 'Roquette au service.'],
  }),
  R('truite-amandes', 'Truite aux amandes, haricots verts & riz complet', {
    tags: ['poisson', 'sans-gluten'], main: 'truite', time: 30, kcal: 540, keeps: 2, freezable: false,
    ing: [['filet de truite', 130, 'g', 'proteines'], ['amandes effilées', 10, 'g', 'epicerie'], ['haricots verts', 150, 'g', 'legumes'],
      ['riz complet', 50, 'g', 'feculents'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire riz et haricots verts.', 'Poêler la truite 3 min par face.', 'Dorer les amandes dans la poêle, verser sur la truite avec le citron.'],
  }),
  R('crevettes-ail-epinards', 'Crevettes sautées à l\'ail, épinards & quinoa', {
    tags: ['poisson', 'sans-gluten'], main: 'crevettes', time: 20, kcal: 450, keeps: 2, freezable: false,
    ing: [['crevettes décortiquées', 110, 'g', 'proteines'], ['épinards frais', 100, 'g', 'legumes'], ['ail', 1, 'gousse', 'legumes'],
      ['quinoa', 60, 'g', 'feculents'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire le quinoa.', 'Sauter ail et crevettes 3 min.', 'Ajouter les épinards jusqu\'à ce qu\'ils tombent. Citron.'],
  }),
];
