// Recettes supplémentaires (quantités POUR 1 PORTION).
// Même format que recipes.js : [nom, quantité, unité ('' = pièce), rayon]

const R = (id, name, o) => {
  const { ing, ...rest } = o;
  return { id: 's-' + id, name, ...rest, ingredients: ing.map(([n, qty, unit, cat]) => ({ name: n, qty, unit, cat })) };
};
const HUILE = ['huile d\'olive', 1, 'c.à.s', 'placard'];

export const EXTRA_RECIPES = [
  // ================= VIANDE =================
  R('poulet-teriyaki', 'Poulet teriyaki, brocoli & riz', {
    tags: ['viande'], main: 'poulet', time: 30, kcal: 540, keeps: 4, freezable: true,
    ing: [['blanc de poulet', 130, 'g', 'proteines'], ['brocoli', 150, 'g', 'legumes'], ['riz basmati', 60, 'g', 'feculents'],
      ['sauce soja', 1, 'c.à.s', 'placard'], ['miel', 0.5, 'c.à.c', 'placard'], ['gingembre frais', 5, 'g', 'legumes'], ['graines de sésame', 5, 'g', 'epicerie']],
    steps: ['Cuire le riz et le brocoli à la vapeur.', 'Dorer le poulet en dés.', 'Ajouter soja, miel et gingembre râpé, laisser caraméliser 3 min.', 'Parsemer de sésame.'],
  }),
  R('poulet-tikka', 'Poulet tikka masala léger & riz', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 40, kcal: 550, keeps: 4, freezable: true,
    ing: [['blanc de poulet', 130, 'g', 'proteines'], ['yaourt grec', 40, 'g', 'cremerie'], ['tomates concassées', 120, 'g', 'epicerie'],
      ['oignon', 0.5, '', 'legumes'], ['ail', 1, 'gousse', 'legumes'], ['gingembre frais', 5, 'g', 'legumes'],
      ['garam masala', 1, 'c.à.c', 'placard'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Mariner le poulet dans la moitié du yaourt et les épices (15 min mini).', 'Faire revenir oignon, ail, gingembre ; ajouter le poulet.',
      'Verser les tomates, mijoter 20 min, finir avec le reste du yaourt hors du feu.', 'Servir avec le riz.'],
  }),
  R('tajine-poulet-citron', 'Tajine de poulet au citron & olives, semoule', {
    tags: ['viande'], main: 'poulet', time: 50, kcal: 560, keeps: 4, freezable: true,
    ing: [['haut de cuisse de poulet', 150, 'g', 'proteines'], ['oignon', 0.5, '', 'legumes'], ['carotte', 1, '', 'legumes'],
      ['olives vertes', 20, 'g', 'epicerie'], ['citron', 0.25, '', 'legumes'], ['ras el hanout', 1, 'c.à.c', 'placard'], ['semoule complète', 60, 'g', 'feculents']],
    steps: ['Dorer le poulet avec l\'oignon et le ras el hanout.', 'Ajouter carottes en rondelles, citron en quartiers et un verre d\'eau.',
      'Mijoter 35 min à couvert, ajouter les olives 5 min avant la fin.', 'Préparer la semoule.'],
  }),
  R('poulet-pesto', 'Poulet au pesto, courgettes & pâtes complètes', {
    tags: ['viande'], main: 'poulet', time: 25, kcal: 570, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['courgette', 1, '', 'legumes'], ['pesto', 15, 'g', 'epicerie'],
      ['pâtes complètes', 70, 'g', 'feculents'], ['tomates cerises', 80, 'g', 'legumes']],
    steps: ['Cuire les pâtes.', 'Sauter le poulet en lanières puis la courgette en demi-rondelles.', 'Mélanger avec pâtes, pesto et tomates coupées.'],
  }),
  R('poulet-champignons', 'Poulet aux champignons & crème légère, riz complet', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 30, kcal: 520, keeps: 3, freezable: true,
    ing: [['blanc de poulet', 130, 'g', 'proteines'], ['champignons de Paris', 120, 'g', 'legumes'], ['crème légère 15 %', 40, 'ml', 'cremerie'],
      ['oignon', 0.5, '', 'legumes'], ['riz complet', 60, 'g', 'feculents'], ['thym', 0.5, 'c.à.c', 'placard']],
    steps: ['Cuire le riz.', 'Dorer le poulet, réserver.', 'Faire revenir oignon et champignons, remettre le poulet, ajouter crème et thym, 5 min.'],
  }),
  R('poulet-satay', 'Poulet sauce cacahuète & nouilles de riz', {
    tags: ['viande'], main: 'poulet', time: 25, kcal: 590, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['beurre de cacahuète', 15, 'g', 'epicerie'], ['sauce soja', 1, 'c.à.s', 'placard'],
      ['carotte', 0.5, '', 'legumes'], ['poivron', 0.5, '', 'legumes'], ['nouilles de riz', 60, 'g', 'feculents'], ['citron vert', 0.25, '', 'legumes']],
    steps: ['Délayer beurre de cacahuète, soja, jus de citron vert et un peu d\'eau chaude.', 'Sauter poulet, carotte et poivron en lanières.',
      'Ajouter nouilles cuites et sauce, mélanger.'],
  }),
  R('dinde-paprika', 'Émincé de dinde au paprika, haricots verts & pommes de terre', {
    tags: ['viande', 'sans-gluten'], main: 'dinde', time: 30, kcal: 470, keeps: 3, freezable: true,
    ing: [['escalope de dinde', 130, 'g', 'proteines'], ['haricots verts', 150, 'g', 'legumes'], ['pommes de terre', 150, 'g', 'feculents'],
      ['oignon', 0.5, '', 'legumes'], ['crème légère 15 %', 30, 'ml', 'cremerie'], ['paprika', 1, 'c.à.c', 'placard']],
    steps: ['Cuire pommes de terre et haricots verts à la vapeur.', 'Dorer l\'oignon et la dinde émincée avec le paprika.', 'Ajouter la crème, 3 min.'],
  }),
  R('curry-dinde-choufleur', 'Curry de dinde, chou-fleur & petits pois', {
    tags: ['viande', 'sans-gluten'], main: 'dinde', time: 35, kcal: 510, keeps: 4, freezable: true,
    ing: [['escalope de dinde', 130, 'g', 'proteines'], ['chou-fleur', 0.25, '', 'legumes'], ['petits pois surgelés', 50, 'g', 'surgeles'],
      ['lait de coco', 40, 'ml', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['curry en poudre', 1, 'c.à.c', 'placard'], ['riz basmati', 50, 'g', 'feculents']],
    steps: ['Faire revenir oignon et curry, ajouter la dinde en dés.', 'Ajouter chou-fleur en petites fleurettes, lait de coco et un peu d\'eau, 15 min.',
      'Ajouter les petits pois 5 min. Servir avec le riz.'],
  }),
  R('boeuf-carottes', 'Bœuf-carottes mijoté & pommes vapeur', {
    tags: ['viande', 'sans-gluten'], main: 'boeuf', time: 150, kcal: 560, keeps: 5, freezable: true,
    ing: [['bœuf à braiser (paleron)', 120, 'g', 'proteines'], ['carotte', 2, '', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['bouillon de légumes (cube)', 0.25, '', 'placard'], ['pommes de terre', 150, 'g', 'feculents'], ['thym', 0.5, 'c.à.c', 'placard']],
    steps: ['Saisir le bœuf en cubes, ajouter l\'oignon.', 'Couvrir de bouillon, ajouter carottes et thym ; mijoter 2 h à feu doux.',
      'Cuire les pommes de terre à la vapeur.'],
  }),
  R('chili-con-carne', 'Chili con carne & riz complet', {
    tags: ['viande', 'sans-gluten'], main: 'boeuf', time: 45, kcal: 590, keeps: 5, freezable: true,
    ing: [['bœuf haché 5 %', 90, 'g', 'proteines'], ['haricots rouges cuits', 90, 'g', 'feculents'], ['tomates concassées', 150, 'g', 'epicerie'],
      ['poivron', 0.5, '', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['maïs en conserve', 30, 'g', 'epicerie'],
      ['riz complet', 50, 'g', 'feculents'], ['cumin', 1, 'c.à.c', 'placard']],
    steps: ['Dorer bœuf, oignon et poivron.', 'Ajouter cumin, tomates, haricots et maïs ; mijoter 30 min.', 'Cuire le riz.'],
  }),
  R('keftas-boeuf', 'Keftas de bœuf, taboulé & yaourt', {
    tags: ['viande'], main: 'boeuf', time: 35, kcal: 590, keeps: 3, freezable: true,
    ing: [['bœuf haché 5 %', 110, 'g', 'proteines'], ['oignon', 0.3, '', 'legumes'], ['persil frais', 0.1, 'botte', 'legumes'],
      ['cumin', 0.5, 'c.à.c', 'placard'], ['boulgour', 60, 'g', 'feculents'], ['concombre', 0.3, '', 'legumes'],
      ['tomates', 1, '', 'legumes'], ['yaourt grec', 40, 'g', 'cremerie']],
    steps: ['Mélanger bœuf, oignon râpé, persil et cumin ; former des boudins.', 'Cuire 15 min au four à 200 °C.',
      'Préparer le boulgour, mélanger avec concombre et tomates en dés.', 'Servir avec le yaourt.'],
  }),
  R('boeuf-basilic', 'Bœuf sauté au basilic thaï, poivrons & riz', {
    tags: ['viande'], main: 'boeuf', time: 25, kcal: 520, keeps: 3, freezable: false,
    ing: [['rumsteck', 110, 'g', 'proteines'], ['poivron', 1, '', 'legumes'], ['basilic frais', 0.1, 'botte', 'legumes'],
      ['ail', 1, 'gousse', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Saisir le bœuf émincé à feu vif, réserver.', 'Sauter ail et poivrons, remettre le bœuf, soja et basilic.'],
  }),
  R('porc-gingembre', 'Sauté de porc au gingembre, bok choy & riz', {
    tags: ['viande'], main: 'porc', time: 30, kcal: 510, keeps: 3, freezable: false,
    ing: [['filet mignon de porc', 120, 'g', 'proteines'], ['bok choy', 1, '', 'legumes'], ['carotte', 0.5, '', 'legumes'],
      ['gingembre frais', 5, 'g', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Saisir le porc émincé.', 'Ajouter carotte, bok choy et gingembre, 4 min.', 'Déglacer à la sauce soja.'],
  }),
  R('porc-lentilles', 'Filet mignon, lentilles vertes & carottes', {
    inDish: ['lentilles vertes'], tags: ['viande', 'sans-gluten'], main: 'porc', time: 50, kcal: 540, keeps: 4, freezable: true,
    ing: [['filet mignon de porc', 120, 'g', 'proteines'], ['lentilles vertes', 60, 'g', 'feculents'], ['carotte', 1, '', 'legumes'],
      ['oignon', 0.5, '', 'legumes'], ['thym', 0.5, 'c.à.c', 'placard'], ['moutarde', 0.5, 'c.à.c', 'placard']],
    steps: ['Faire revenir oignon et carotte, ajouter lentilles, thym et 3 fois leur volume d\'eau ; 25 min.',
      'Rôtir le filet mignon badigeonné de moutarde 20 min à 180 °C.', 'Trancher et servir sur les lentilles.'],
  }),
  R('endives-jambon', 'Endives au jambon gratinées (version légère)', {
    tags: ['viande'], main: 'porc', time: 50, kcal: 420, keeps: 3, freezable: true,
    ing: [['endives', 2, '', 'legumes'], ['jambon blanc', 2, 'tranche', 'proteines'], ['lait demi-écrémé', 100, 'ml', 'cremerie'],
      ['farine', 8, 'g', 'epicerie'], ['emmental râpé', 15, 'g', 'cremerie']],
    steps: ['Cuire les endives 10 min à la vapeur, bien égoutter.', 'Préparer une béchamel légère avec lait et farine.',
      'Rouler chaque endive dans une tranche de jambon, napper, parsemer d\'emmental.', 'Gratiner 20 min à 200 °C.'],
  }),
  R('lasagnes-courgette-dinde', 'Lasagnes de courgettes à la dinde', {
    tags: ['viande', 'sans-gluten'], main: 'dinde', time: 55, kcal: 450, keeps: 4, freezable: true,
    ing: [['dinde hachée', 110, 'g', 'proteines'], ['courgette', 1, '', 'legumes'], ['coulis de tomate', 120, 'g', 'epicerie'],
      ['ricotta', 40, 'g', 'cremerie'], ['mozzarella', 25, 'g', 'cremerie'], ['herbes de Provence', 0.5, 'c.à.c', 'placard']],
    steps: ['Trancher les courgettes en lamelles fines dans la longueur.', 'Cuire la dinde avec le coulis et les herbes 10 min.',
      'Alterner courgettes, sauce et ricotta ; finir par la mozzarella.', 'Cuire 35 min à 180 °C.'],
  }),
  R('burrito-bowl', 'Burrito bowl poulet, haricots noirs & maïs', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 30, kcal: 610, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 120, 'g', 'proteines'], ['haricots noirs cuits', 80, 'g', 'feculents'], ['maïs en conserve', 40, 'g', 'epicerie'],
      ['riz complet', 50, 'g', 'feculents'], ['avocat', 0.3, '', 'legumes'], ['tomates', 1, '', 'legumes'],
      ['citron vert', 0.25, '', 'legumes'], ['paprika', 1, 'c.à.c', 'placard']],
    steps: ['Cuire le riz.', 'Griller le poulet au paprika, le trancher.', 'Assembler riz, haricots, maïs, tomates et poulet.',
      'Ajouter l\'avocat et le citron vert au moment de manger.'],
  }),
  R('pho-poulet', 'Soupe pho au poulet', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 35, kcal: 420, keeps: 3, freezable: true,
    ing: [['blanc de poulet', 100, 'g', 'proteines'], ['nouilles de riz', 50, 'g', 'feculents'], ['bouillon de volaille (cube)', 0.5, '', 'placard'],
      ['gingembre frais', 5, 'g', 'legumes'], ['oignon', 0.3, '', 'legumes'], ['bok choy', 0.5, '', 'legumes'],
      ['citron vert', 0.25, '', 'legumes'], ['coriandre fraîche', 0.1, 'botte', 'legumes']],
    steps: ['Faire infuser bouillon, gingembre et oignon 15 min (400 ml par portion).', 'Pocher le poulet 10 min dans le bouillon, l\'effilocher.',
      'Conserver bouillon et nouilles séparément.', 'Au moment de servir : nouilles, bok choy, bouillon chaud, coriandre, citron vert.'],
  }),
  R('poivrons-farcis', 'Poivrons farcis dinde & quinoa', {
    tags: ['viande', 'sans-gluten'], main: 'dinde', time: 50, kcal: 470, keeps: 4, freezable: true,
    ing: [['dinde hachée', 100, 'g', 'proteines'], ['poivron', 1, '', 'legumes'], ['quinoa', 40, 'g', 'feculents'],
      ['tomates concassées', 80, 'g', 'epicerie'], ['oignon', 0.3, '', 'legumes'], ['emmental râpé', 15, 'g', 'cremerie']],
    steps: ['Cuire le quinoa.', 'Faire revenir oignon et dinde, ajouter tomates et quinoa.', 'Farcir les poivrons coupés en deux, parsemer d\'emmental.',
      'Cuire 30 min à 190 °C.'],
  }),
  R('paella-poulet', 'Paella express au poulet & légumes', {
    inDish: ['riz basmati'], tags: ['viande', 'sans-gluten'], main: 'poulet', time: 40, kcal: 560, keeps: 3, freezable: false,
    ing: [['haut de cuisse de poulet', 120, 'g', 'proteines'], ['riz basmati', 70, 'g', 'feculents'], ['poivron', 0.5, '', 'legumes'],
      ['petits pois surgelés', 40, 'g', 'surgeles'], ['tomates concassées', 80, 'g', 'epicerie'], ['curcuma', 0.5, 'c.à.c', 'placard'],
      ['paprika', 0.5, 'c.à.c', 'placard'], ['bouillon de volaille (cube)', 0.25, '', 'placard']],
    steps: ['Dorer le poulet en morceaux avec le poivron.', 'Ajouter riz, épices et tomates, puis 2 fois le volume de riz en bouillon.',
      'Cuire 18 min sans remuer, ajouter les petits pois 5 min avant la fin.'],
  }),
  R('chili-dinde-patate', 'Chili de dinde, haricots noirs & patate douce', {
    tags: ['viande', 'sans-gluten'], main: 'dinde', time: 45, kcal: 500, keeps: 5, freezable: true,
    ing: [['dinde hachée', 100, 'g', 'proteines'], ['haricots noirs cuits', 80, 'g', 'feculents'], ['patate douce', 120, 'g', 'legumes'],
      ['tomates concassées', 120, 'g', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['cumin', 1, 'c.à.c', 'placard'], ['paprika fumé', 0.5, 'c.à.c', 'placard']],
    steps: ['Dorer oignon et dinde avec les épices.', 'Ajouter patate douce en petits dés, tomates et un verre d\'eau ; mijoter 25 min.', 'Ajouter les haricots, 5 min.'],
  }),
  R('salade-poulet-lentilles', 'Salade-repas poulet, lentilles & crudités', {
    tags: ['viande', 'sans-gluten'], main: 'poulet', time: 30, kcal: 470, keeps: 3, freezable: false,
    ing: [['blanc de poulet', 100, 'g', 'proteines'], ['lentilles vertes', 50, 'g', 'feculents'], ['carotte', 0.5, '', 'legumes'],
      ['concombre', 0.3, '', 'legumes'], ['tomates cerises', 80, 'g', 'legumes'], ['moutarde', 0.5, 'c.à.c', 'placard'], HUILE],
    steps: ['Cuire les lentilles 20 min, refroidir.', 'Griller et trancher le poulet.', 'Couper les crudités.',
      'Vinaigrette moutarde-huile à part, à ajouter au moment de manger.'],
  }),

  // ================= POISSON =================
  R('saumon-poireaux', 'Saumon aux poireaux fondants & riz complet', {
    tags: ['poisson', 'sans-gluten'], main: 'saumon', time: 35, kcal: 590, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 130, 'g', 'proteines'], ['poireau', 1, '', 'legumes'], ['crème légère 15 %', 30, 'ml', 'cremerie'],
      ['riz complet', 60, 'g', 'feculents'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire le riz.', 'Faire fondre les poireaux émincés 15 min à couvert, ajouter la crème.', 'Cuire le saumon 10 min au four à 200 °C, arroser de citron.'],
  }),
  R('curry-cabillaud', 'Curry de cabillaud au lait de coco & riz', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 30, kcal: 470, keeps: 2, freezable: true,
    ing: [['dos de cabillaud', 140, 'g', 'proteines'], ['lait de coco', 50, 'ml', 'epicerie'], ['tomates concassées', 100, 'g', 'epicerie'],
      ['épinards frais', 50, 'g', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['curry en poudre', 1, 'c.à.c', 'placard'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Faire revenir oignon et curry, ajouter tomates et lait de coco, 10 min.', 'Déposer le cabillaud en morceaux, pocher 8 min.',
      'Ajouter les épinards. Servir avec le riz.'],
  }),
  R('salade-nicoise', 'Salade niçoise complète', {
    tags: ['poisson', 'sans-gluten'], main: 'thon', time: 30, kcal: 480, keeps: 3, freezable: false,
    ing: [['thon au naturel', 80, 'g', 'epicerie'], ['œufs', 1, '', 'cremerie'], ['haricots verts', 100, 'g', 'legumes'],
      ['pommes de terre', 120, 'g', 'feculents'], ['tomates', 1, '', 'legumes'], ['olives noires', 15, 'g', 'epicerie'], HUILE],
    steps: ['Cuire pommes de terre et haricots verts, refroidir.', 'Œufs durs 10 min.', 'Assembler avec tomates, thon et olives ; huile au moment de servir.'],
  }),
  R('curry-rouge-crevettes', 'Curry rouge de crevettes & légumes, riz', {
    tags: ['poisson', 'sans-gluten'], main: 'crevettes', time: 25, kcal: 480, keeps: 2, freezable: false,
    ing: [['crevettes décortiquées', 120, 'g', 'proteines'], ['lait de coco', 50, 'ml', 'epicerie'], ['pâte de curry', 1, 'c.à.c', 'epicerie'],
      ['poivron', 0.5, '', 'legumes'], ['courgette', 0.5, '', 'legumes'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Faire revenir la pâte de curry, ajouter lait de coco, poivron et courgette, 8 min.', 'Ajouter les crevettes 3 min.'],
  }),
  R('pates-sardines', 'Pâtes complètes aux sardines, brocoli & citron', {
    tags: ['poisson'], main: 'sardines', time: 20, kcal: 560, keeps: 2, freezable: false,
    ing: [['sardines à l\'huile', 70, 'g', 'epicerie'], ['pâtes complètes', 80, 'g', 'feculents'], ['brocoli', 120, 'g', 'legumes'],
      ['ail', 1, 'gousse', 'legumes'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire pâtes et brocoli ensemble (brocoli les 5 dernières minutes).', 'Faire revenir l\'ail dans un peu d\'huile des sardines.',
      'Mélanger avec les sardines émiettées, zeste et jus de citron.'],
  }),
  R('lentilles-maquereau', 'Salade de lentilles au maquereau', {
    tags: ['poisson', 'sans-gluten'], main: 'maquereau', time: 25, kcal: 520, keeps: 3, freezable: false,
    ing: [['maquereau en conserve', 80, 'g', 'epicerie'], ['lentilles vertes', 60, 'g', 'feculents'], ['échalote', 0.3, '', 'legumes'],
      ['carotte', 0.5, '', 'legumes'], ['moutarde', 0.5, 'c.à.c', 'placard'], ['vinaigre de cidre', 1, 'c.à.c', 'placard']],
    steps: ['Cuire les lentilles 20 min, égoutter.', 'Ajouter échalote ciselée, carotte râpée, moutarde et vinaigre.', 'Émietter le maquereau au moment de servir.'],
  }),
  R('truite-quinoa', 'Truite, quinoa & légumes rôtis', {
    tags: ['poisson', 'sans-gluten'], main: 'truite', time: 35, kcal: 520, keeps: 2, freezable: false,
    ing: [['filet de truite', 130, 'g', 'proteines'], ['quinoa', 60, 'g', 'feculents'], ['courgette', 0.5, '', 'legumes'],
      ['poivron', 0.5, '', 'legumes'], ['citron', 0.25, '', 'legumes'], HUILE],
    steps: ['Rôtir courgette et poivron en dés 20 min à 200 °C.', 'Cuire le quinoa.', 'Ajouter la truite sur la plaque 10 min. Citron.'],
  }),
  R('colin-provencale', 'Colin à la provençale & semoule complète', {
    tags: ['poisson'], main: 'poisson-blanc', time: 30, kcal: 430, keeps: 2, freezable: true,
    ing: [['filet de colin', 140, 'g', 'proteines'], ['tomates concassées', 120, 'g', 'epicerie'], ['courgette', 0.5, '', 'legumes'],
      ['olives noires', 10, 'g', 'epicerie'], ['ail', 1, 'gousse', 'legumes'], ['semoule complète', 60, 'g', 'feculents'],
      ['herbes de Provence', 0.5, 'c.à.c', 'placard']],
    steps: ['Mijoter ail, courgette, tomates et herbes 15 min.', 'Déposer le colin et les olives, couvrir 8 min.', 'Préparer la semoule.'],
  }),
  R('tacos-poisson', 'Tacos de poisson, chou croquant & yaourt citronné', {
    tags: ['poisson'], main: 'poisson-blanc', time: 25, kcal: 500, keeps: 2, freezable: false,
    ing: [['filet de colin', 120, 'g', 'proteines'], ['tortillas complètes', 2, '', 'feculents'], ['chou rouge', 60, 'g', 'legumes'],
      ['yaourt grec', 30, 'g', 'cremerie'], ['citron vert', 0.25, '', 'legumes'], ['paprika', 0.5, 'c.à.c', 'placard']],
    steps: ['Cuire le colin au paprika à la poêle, l\'émietter.', 'Émincer finement le chou.', 'Mélanger yaourt et citron vert.', 'Garnir les tortillas au moment de manger.'],
  }),
  R('poke-saumon', 'Poke bowl saumon rôti, riz & edamame', {
    tags: ['poisson'], main: 'saumon', time: 30, kcal: 600, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 110, 'g', 'proteines'], ['riz basmati', 60, 'g', 'feculents'], ['edamame surgelés', 50, 'g', 'surgeles'],
      ['concombre', 0.3, '', 'legumes'], ['avocat', 0.3, '', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'], ['graines de sésame', 5, 'g', 'epicerie']],
    steps: ['Cuire riz et edamame.', 'Rôtir le saumon 10 min à 200 °C, l\'émietter en gros morceaux.', 'Assembler ; avocat et sauce soja au moment de manger.'],
  }),
  R('riz-cantonais-crevettes', 'Riz sauté aux crevettes & œuf', {
    tags: ['poisson'], main: 'crevettes', time: 25, kcal: 500, keeps: 3, freezable: false,
    ing: [['crevettes décortiquées', 80, 'g', 'proteines'], ['œufs', 1, '', 'cremerie'], ['riz basmati', 60, 'g', 'feculents'],
      ['petits pois surgelés', 40, 'g', 'surgeles'], ['carotte', 0.5, '', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard']],
    steps: ['Cuire le riz (idéalement la veille).', 'Brouiller les œufs, réserver.', 'Sauter carotte en dés, petits pois et crevettes.', 'Ajouter riz, œufs et soja, sauter 3 min.'],
  }),
  R('gratin-poisson-epinards', 'Gratin de poisson blanc aux épinards', {
    tags: ['poisson'], main: 'poisson-blanc', time: 45, kcal: 450, keeps: 3, freezable: true,
    ing: [['filet de colin', 130, 'g', 'proteines'], ['épinards frais', 150, 'g', 'legumes'], ['lait demi-écrémé', 80, 'ml', 'cremerie'],
      ['farine', 8, 'g', 'epicerie'], ['emmental râpé', 15, 'g', 'cremerie'], ['pommes de terre', 120, 'g', 'feculents']],
    steps: ['Cuire les pommes de terre en rondelles 10 min.', 'Faire tomber les épinards. Préparer une béchamel légère.',
      'Monter pommes de terre, épinards, poisson, béchamel, emmental.', 'Cuire 25 min à 190 °C.'],
  }),
  R('quiche-saumon-brocoli', 'Quiche sans pâte saumon & brocoli', {
    tags: ['poisson', 'sans-gluten'], main: 'saumon', time: 45, kcal: 430, keeps: 3, freezable: true,
    ing: [['pavé de saumon', 70, 'g', 'proteines'], ['brocoli', 100, 'g', 'legumes'], ['œufs', 2, '', 'cremerie'],
      ['lait demi-écrémé', 60, 'ml', 'cremerie'], ['emmental râpé', 15, 'g', 'cremerie'], ['salade verte', 40, 'g', 'legumes']],
    steps: ['Précuire le brocoli 5 min.', 'Battre œufs, lait, emmental ; ajouter brocoli et saumon en dés.', 'Cuire 30 min à 180 °C. Servir avec la salade.'],
  }),
  R('galettes-thon', 'Galettes thon & pois chiches, salade et yaourt', {
    tags: ['poisson'], main: 'thon', time: 30, kcal: 460, keeps: 3, freezable: true,
    ing: [['thon au naturel', 70, 'g', 'epicerie'], ['pois chiches cuits', 80, 'g', 'feculents'], ['œufs', 0.5, '', 'cremerie'],
      ['flocons d\'avoine', 15, 'g', 'feculents'], ['persil frais', 0.1, 'botte', 'legumes'], ['salade verte', 40, 'g', 'legumes'], ['yaourt grec', 30, 'g', 'cremerie']],
    steps: ['Écraser pois chiches et thon, ajouter œuf, avoine et persil.', 'Former des galettes, cuire 20 min à 200 °C.', 'Servir avec salade et yaourt.'],
  }),
  R('orzotto-crevettes', 'Orzotto crevettes, courgette & citron', {
    tags: ['poisson'], main: 'crevettes', time: 40, kcal: 520, keeps: 2, freezable: false,
    ing: [['orge perlé', 70, 'g', 'feculents'], ['crevettes décortiquées', 90, 'g', 'proteines'], ['courgette', 0.5, '', 'legumes'],
      ['oignon', 0.3, '', 'legumes'], ['parmesan', 10, 'g', 'cremerie'], ['citron', 0.25, '', 'legumes'], ['bouillon de légumes (cube)', 0.25, '', 'placard']],
    steps: ['Faire revenir l\'oignon, ajouter l\'orge puis le bouillon petit à petit, 30 min.', 'Ajouter courgette râpée et crevettes, 4 min.',
      'Finir avec parmesan et zeste de citron.'],
  }),
  R('merlu-herbes', 'Merlu en croûte d\'herbes & patate douce rôtie', {
    tags: ['poisson'], main: 'poisson-blanc', time: 35, kcal: 470, keeps: 2, freezable: false,
    ing: [['filet de merlu', 140, 'g', 'proteines'], ['flocons d\'avoine', 15, 'g', 'feculents'], ['persil frais', 0.1, 'botte', 'legumes'],
      ['patate douce', 180, 'g', 'legumes'], HUILE],
    steps: ['Rôtir la patate douce en frites 25 min à 200 °C.', 'Mixer avoine, persil et un filet d\'huile ; en couvrir le merlu.', 'Ajouter le merlu sur la plaque 12 min.'],
  }),
  R('miso-saumon-soba', 'Soupe miso au saumon & nouilles soba', {
    tags: ['poisson'], main: 'saumon', time: 25, kcal: 440, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 100, 'g', 'proteines'], ['nouilles soba', 50, 'g', 'feculents'], ['pâte miso', 1, 'c.à.s', 'epicerie'],
      ['bok choy', 0.5, '', 'legumes'], ['champignons de Paris', 50, 'g', 'legumes'], ['oignon nouveau', 0.5, '', 'legumes']],
    steps: ['Pocher le saumon et les champignons 8 min dans 400 ml d\'eau par portion.', 'Hors du feu, délayer le miso (ne pas faire bouillir).',
      'Conserver les soba à part ; ajouter bok choy et oignon nouveau au réchauffage.'],
  }),
  R('wraps-thon', 'Wraps au thon, crudités & fromage frais', {
    tags: ['poisson'], main: 'thon', time: 15, kcal: 480, keeps: 2, freezable: false,
    ing: [['thon au naturel', 70, 'g', 'epicerie'], ['tortillas complètes', 2, '', 'feculents'], ['fromage frais', 30, 'g', 'cremerie'],
      ['carotte', 0.5, '', 'legumes'], ['salade verte', 30, 'g', 'legumes'], ['tomates', 1, '', 'legumes']],
    steps: ['Mélanger thon et fromage frais.', 'Râper la carotte, couper les tomates.', 'Garnir et rouler les wraps le jour même (garniture prête à l\'avance).'],
  }),
  R('cabillaud-pois-chiches', 'Cabillaud rôti, pois chiches & tomates à la marocaine', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 30, kcal: 460, keeps: 2, freezable: false,
    ing: [['dos de cabillaud', 130, 'g', 'proteines'], ['pois chiches cuits', 80, 'g', 'feculents'], ['tomates cerises', 100, 'g', 'legumes'],
      ['ras el hanout', 1, 'c.à.c', 'placard'], ['citron', 0.25, '', 'legumes'], HUILE],
    steps: ['Mélanger pois chiches, tomates, ras el hanout et huile sur une plaque, 15 min à 200 °C.', 'Ajouter le cabillaud, 12 min.', 'Arroser de citron.'],
  }),
  R('pates-crevettes', 'Pâtes complètes aux crevettes, ail & tomates cerises', {
    tags: ['poisson'], main: 'crevettes', time: 20, kcal: 540, keeps: 2, freezable: false,
    ing: [['crevettes décortiquées', 100, 'g', 'proteines'], ['pâtes complètes', 80, 'g', 'feculents'], ['tomates cerises', 100, 'g', 'legumes'],
      ['ail', 1, 'gousse', 'legumes'], ['persil frais', 0.1, 'botte', 'legumes'], HUILE],
    steps: ['Cuire les pâtes.', 'Faire revenir ail et tomates coupées 5 min.', 'Ajouter crevettes 3 min, puis pâtes et persil.'],
  }),
  R('saumon-beluga', 'Saumon, lentilles beluga & poireaux', {
    tags: ['poisson', 'sans-gluten'], main: 'saumon', time: 30, kcal: 560, keeps: 2, freezable: false,
    ing: [['pavé de saumon', 120, 'g', 'proteines'], ['lentilles beluga', 60, 'g', 'feculents'], ['poireau', 0.5, '', 'legumes'],
      ['moutarde', 0.5, 'c.à.c', 'placard'], ['citron', 0.25, '', 'legumes']],
    steps: ['Cuire les lentilles 20 min.', 'Faire fondre le poireau, mélanger aux lentilles avec la moutarde.', 'Cuire le saumon 10 min au four, citron.'],
  }),
  R('brandade-colin', 'Brandade légère de colin & salade', {
    tags: ['poisson', 'sans-gluten'], main: 'poisson-blanc', time: 45, kcal: 450, keeps: 3, freezable: true,
    ing: [['filet de colin', 120, 'g', 'proteines'], ['pommes de terre', 180, 'g', 'feculents'], ['lait demi-écrémé', 60, 'ml', 'cremerie'],
      ['ail', 1, 'gousse', 'legumes'], ['salade verte', 40, 'g', 'legumes'], HUILE],
    steps: ['Cuire les pommes de terre ; pocher le colin 8 min dans le lait avec l\'ail.', 'Écraser le tout avec l\'huile.',
      'Gratiner 15 min à 200 °C. Servir avec la salade.'],
  }),

  // ================= VÉGÉTARIEN / VEGAN =================
  R('lasagnes-epinards', 'Lasagnes épinards-ricotta', {
    tags: ['vegetarien'], main: 'fromage', time: 60, kcal: 520, keeps: 4, freezable: true,
    ing: [['plaques de lasagne', 60, 'g', 'feculents'], ['épinards frais', 100, 'g', 'legumes'], ['ricotta', 50, 'g', 'cremerie'],
      ['coulis de tomate', 120, 'g', 'epicerie'], ['mozzarella', 25, 'g', 'cremerie'], ['ail', 1, 'gousse', 'legumes']],
    steps: ['Faire tomber les épinards avec l\'ail, mélanger à la ricotta.', 'Alterner coulis, plaques, épinards-ricotta.', 'Finir par coulis et mozzarella, cuire 40 min à 180 °C.'],
  }),
  R('enchiladas-haricots', 'Enchiladas aux haricots noirs & maïs', {
    tags: ['vegetarien'], main: 'legumineuses', time: 40, kcal: 580, keeps: 3, freezable: true,
    ing: [['tortillas complètes', 2, '', 'feculents'], ['haricots noirs cuits', 90, 'g', 'feculents'], ['maïs en conserve', 40, 'g', 'epicerie'],
      ['poivron', 0.5, '', 'legumes'], ['coulis de tomate', 100, 'g', 'epicerie'], ['emmental râpé', 20, 'g', 'cremerie'], ['cumin', 0.5, 'c.à.c', 'placard']],
    steps: ['Sauter poivron, haricots, maïs et cumin.', 'Garnir et rouler les tortillas dans un plat.', 'Napper de coulis, parsemer d\'emmental, 20 min à 200 °C.'],
  }),
  R('falafels-four', 'Falafels au four, boulgour & sauce yaourt', {
    tags: ['vegetarien'], main: 'legumineuses', time: 45, kcal: 540, keeps: 4, freezable: true,
    ing: [['pois chiches cuits', 120, 'g', 'feculents'], ['oignon', 0.3, '', 'legumes'], ['persil frais', 0.1, 'botte', 'legumes'],
      ['cumin', 1, 'c.à.c', 'placard'], ['farine', 10, 'g', 'epicerie'], ['boulgour', 50, 'g', 'feculents'],
      ['yaourt grec', 40, 'g', 'cremerie'], ['concombre', 0.3, '', 'legumes']],
    steps: ['Mixer pois chiches, oignon, persil, cumin et farine.', 'Former des boulettes, cuire 25 min à 200 °C en les retournant.',
      'Cuire le boulgour.', 'Sauce : yaourt + concombre râpé.'],
  }),
  R('curry-lentilles-butternut', 'Curry de lentilles vertes & butternut', {
    inDish: ['lentilles vertes'], tags: ['vegan', 'sans-gluten'], main: 'legumineuses', time: 45, kcal: 500, keeps: 5, freezable: true,
    ing: [['lentilles vertes', 60, 'g', 'feculents'], ['courge butternut', 150, 'g', 'legumes'], ['lait de coco', 40, 'ml', 'epicerie'],
      ['tomates concassées', 100, 'g', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['curry en poudre', 1, 'c.à.c', 'placard'], ['riz basmati', 40, 'g', 'feculents']],
    steps: ['Faire revenir oignon et curry.', 'Ajouter lentilles, butternut en dés, tomates, lait de coco et 2 verres d\'eau ; 30 min.', 'Servir avec le riz.'],
  }),
  R('tofu-aigre-doux', 'Tofu croustillant aigre-doux, poivrons & riz', {
    tags: ['vegan'], main: 'tofu', time: 30, kcal: 520, keeps: 3, freezable: false,
    ing: [['tofu ferme', 120, 'g', 'proteines'], ['poivron', 1, '', 'legumes'], ['fécule de maïs', 5, 'g', 'epicerie'],
      ['sauce soja', 1, 'c.à.s', 'placard'], ['sirop d\'érable', 0.5, 'c.à.c', 'placard'], ['vinaigre de riz', 0.5, 'c.à.s', 'placard'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Rouler le tofu en cubes dans la fécule, cuire 25 min à 200 °C.', 'Sauter les poivrons.',
      'Mélanger soja, sirop et vinaigre, enrober tofu et poivrons.', 'Servir avec le riz.'],
  }),
  R('pad-thai-tofu', 'Pad thaï au tofu & cacahuètes', {
    tags: ['vegetarien'], main: 'tofu', time: 30, kcal: 560, keeps: 2, freezable: false,
    ing: [['nouilles de riz', 70, 'g', 'feculents'], ['tofu ferme', 100, 'g', 'proteines'], ['œufs', 0.5, '', 'cremerie'],
      ['carotte', 0.5, '', 'legumes'], ['pousses de soja', 50, 'g', 'legumes'], ['cacahuètes', 10, 'g', 'epicerie'],
      ['sauce soja', 1, 'c.à.s', 'placard'], ['citron vert', 0.25, '', 'legumes']],
    steps: ['Tremper ou cuire les nouilles.', 'Dorer le tofu, brouiller l\'œuf dans la poêle.', 'Ajouter carotte, pousses, nouilles et soja.',
      'Cacahuètes concassées et citron vert au moment de servir.'],
  }),
  R('risotto-petits-pois', 'Risotto petits pois, menthe & parmesan', {
    tags: ['vegetarien', 'sans-gluten'], main: 'cereales', time: 35, kcal: 480, keeps: 2, freezable: false,
    ing: [['riz rond (arborio)', 70, 'g', 'feculents'], ['petits pois surgelés', 80, 'g', 'surgeles'], ['oignon', 0.3, '', 'legumes'],
      ['parmesan', 15, 'g', 'cremerie'], ['menthe fraîche', 0.1, 'botte', 'legumes'], ['bouillon de légumes (cube)', 0.25, '', 'placard']],
    steps: ['Nacrer le riz avec l\'oignon.', 'Ajouter le bouillon louche par louche, 18 min.', 'Ajouter petits pois 5 min, puis parmesan et menthe.'],
  }),
  R('gnocchis-epinards', 'Gnocchis poêlés, épinards & tomates cerises', {
    tags: ['vegetarien'], main: 'cereales', time: 15, kcal: 470, keeps: 2, freezable: false,
    ing: [['gnocchis', 150, 'g', 'feculents'], ['épinards frais', 80, 'g', 'legumes'], ['tomates cerises', 100, 'g', 'legumes'],
      ['parmesan', 10, 'g', 'cremerie'], ['ail', 1, 'gousse', 'legumes']],
    steps: ['Dorer les gnocchis à la poêle 6 min.', 'Ajouter ail, tomates coupées et épinards, 3 min.', 'Parmesan au moment de servir.'],
  }),
  R('soupe-carotte-lentilles', 'Soupe carotte, lentilles corail & cumin', {
    tags: ['vegan'], main: 'legumineuses', time: 35, kcal: 420, keeps: 5, freezable: true,
    ing: [['carotte', 2, '', 'legumes'], ['lentilles corail', 50, 'g', 'feculents'], ['oignon', 0.5, '', 'legumes'],
      ['lait de coco', 30, 'ml', 'epicerie'], ['cumin', 1, 'c.à.c', 'placard'], ['pain complet', 50, 'g', 'feculents']],
    steps: ['Faire revenir oignon et cumin.', 'Ajouter carottes, lentilles et 350 ml d\'eau par portion ; 25 min.', 'Mixer avec le lait de coco. Servir avec le pain.'],
  }),
  R('soupe-pois-casses', 'Soupe de pois cassés & carottes', {
    tags: ['vegan'], main: 'legumineuses', time: 60, kcal: 410, keeps: 5, freezable: true,
    ing: [['pois cassés', 70, 'g', 'feculents'], ['carotte', 1, '', 'legumes'], ['oignon', 0.5, '', 'legumes'],
      ['poireau', 0.3, '', 'legumes'], ['bouillon de légumes (cube)', 0.25, '', 'placard'], ['pain complet', 40, 'g', 'feculents']],
    steps: ['Rincer les pois cassés.', 'Les cuire 50 min avec légumes et bouillon (400 ml par portion).', 'Mixer. Servir avec le pain.'],
  }),
  R('harira', 'Harira aux pois chiches & lentilles', {
    inDish: ['lentilles vertes'], tags: ['vegan'], main: 'legumineuses', time: 50, kcal: 430, keeps: 5, freezable: true,
    ing: [['pois chiches cuits', 60, 'g', 'feculents'], ['lentilles vertes', 30, 'g', 'feculents'], ['tomates concassées', 120, 'g', 'epicerie'],
      ['céleri branche', 0.3, '', 'legumes'], ['oignon', 0.5, '', 'legumes'], ['coriandre fraîche', 0.1, 'botte', 'legumes'],
      ['ras el hanout', 1, 'c.à.c', 'placard'], ['petites pâtes', 20, 'g', 'feculents']],
    steps: ['Faire revenir oignon et céleri avec les épices.', 'Ajouter tomates, lentilles et 350 ml d\'eau par portion ; 30 min.',
      'Ajouter pois chiches et pâtes 10 min. Coriandre au service.'],
  }),
  R('bowl-tahini', 'Bowl patate douce rôtie, quinoa, pois chiches & tahini', {
    tags: ['vegan', 'sans-gluten'], main: 'legumineuses', time: 35, kcal: 560, keeps: 4, freezable: false,
    ing: [['patate douce', 150, 'g', 'legumes'], ['quinoa', 50, 'g', 'feculents'], ['pois chiches cuits', 80, 'g', 'feculents'],
      ['épinards frais', 40, 'g', 'legumes'], ['tahini (purée de sésame)', 15, 'g', 'epicerie'], ['citron', 0.25, '', 'legumes']],
    steps: ['Rôtir patate douce et pois chiches 25 min à 200 °C.', 'Cuire le quinoa.', 'Sauce : tahini + citron + eau.', 'Assembler sur les épinards.'],
  }),
  R('clafoutis-courgette', 'Clafoutis courgette-chèvre & salade', {
    tags: ['vegetarien'], main: 'oeuf', time: 45, kcal: 400, keeps: 3, freezable: false,
    ing: [['courgette', 1, '', 'legumes'], ['œufs', 1.5, '', 'cremerie'], ['lait demi-écrémé', 60, 'ml', 'cremerie'],
      ['chèvre frais', 30, 'g', 'cremerie'], ['farine', 10, 'g', 'epicerie'], ['salade verte', 40, 'g', 'legumes']],
    steps: ['Faire revenir la courgette en dés.', 'Battre œufs, farine et lait.', 'Ajouter courgette et chèvre émietté, cuire 30 min à 180 °C.'],
  }),
  R('tortilla-espagnole', 'Tortilla espagnole & salade de tomates', {
    tags: ['vegetarien', 'sans-gluten'], main: 'oeuf', time: 40, kcal: 450, keeps: 3, freezable: false,
    ing: [['œufs', 2, '', 'cremerie'], ['pommes de terre', 150, 'g', 'feculents'], ['oignon', 0.5, '', 'legumes'],
      ['tomates', 1, '', 'legumes'], HUILE],
    steps: ['Cuire pommes de terre en fines rondelles et oignon à la poêle 20 min.', 'Verser les œufs battus, cuire à feu doux à couvert, retourner.', 'Servir avec les tomates.'],
  }),
  R('galettes-legumes-houmous', 'Galettes de légumes, houmous & salade', {
    tags: ['vegetarien'], main: 'legumineuses', time: 35, kcal: 470, keeps: 3, freezable: true,
    ing: [['courgette', 0.5, '', 'legumes'], ['carotte', 0.5, '', 'legumes'], ['œufs', 0.5, '', 'cremerie'],
      ['flocons d\'avoine', 20, 'g', 'feculents'], ['houmous', 50, 'g', 'epicerie'], ['salade verte', 40, 'g', 'legumes'], ['pain complet', 40, 'g', 'feculents']],
    steps: ['Râper courgette et carotte, presser pour retirer l\'eau.', 'Mélanger avec œuf et avoine, former des galettes.', 'Cuire 20 min à 200 °C.'],
  }),
  R('ragout-toscan', 'Ragoût toscan de haricots blancs & épinards', {
    tags: ['vegetarien'], main: 'legumineuses', time: 30, kcal: 480, keeps: 5, freezable: true,
    ing: [['haricots blancs cuits', 140, 'g', 'feculents'], ['tomates concassées', 120, 'g', 'epicerie'], ['épinards frais', 60, 'g', 'legumes'],
      ['ail', 1, 'gousse', 'legumes'], ['romarin', 0.5, 'c.à.c', 'placard'], ['parmesan', 10, 'g', 'cremerie'], ['pain complet', 50, 'g', 'feculents']],
    steps: ['Faire revenir ail et romarin.', 'Ajouter tomates et haricots, mijoter 15 min.', 'Ajouter les épinards. Parmesan et pain au service.'],
  }),
  R('pates-ligure', 'Pâtes au pesto, haricots verts & pommes de terre', {
    tags: ['vegetarien'], main: 'cereales', time: 25, kcal: 560, keeps: 3, freezable: false,
    ing: [['pâtes complètes', 70, 'g', 'feculents'], ['pesto', 20, 'g', 'epicerie'], ['haricots verts', 80, 'g', 'legumes'],
      ['pommes de terre', 80, 'g', 'feculents'], ['parmesan', 10, 'g', 'cremerie']],
    steps: ['Cuire les pommes de terre en dés 5 min, ajouter pâtes et haricots verts.', 'Égoutter, mélanger avec le pesto.', 'Parmesan au service.'],
  }),
  R('tofu-champignons', 'Tofu braisé aux champignons, sauce soja & riz', {
    tags: ['vegan'], main: 'tofu', time: 25, kcal: 470, keeps: 3, freezable: false,
    ing: [['tofu ferme', 130, 'g', 'proteines'], ['champignons de Paris', 100, 'g', 'legumes'], ['sauce soja', 1, 'c.à.s', 'placard'],
      ['gingembre frais', 5, 'g', 'legumes'], ['ail', 1, 'gousse', 'legumes'], ['oignon nouveau', 0.5, '', 'legumes'], ['riz basmati', 60, 'g', 'feculents']],
    steps: ['Cuire le riz.', 'Sauter ail, gingembre et champignons.', 'Ajouter le tofu en cubes, soja et un peu d\'eau, braiser 8 min.', 'Oignon nouveau au service.'],
  }),
  R('moussaka-lentilles', 'Moussaka végétarienne aux lentilles', {
    inDish: ['lentilles vertes'], tags: ['vegetarien', 'sans-gluten'], main: 'legumineuses', time: 70, kcal: 450, keeps: 4, freezable: true,
    ing: [['aubergine', 0.5, '', 'legumes'], ['lentilles vertes', 50, 'g', 'feculents'], ['tomates concassées', 120, 'g', 'epicerie'],
      ['oignon', 0.5, '', 'legumes'], ['yaourt grec', 50, 'g', 'cremerie'], ['œufs', 0.3, '', 'cremerie'], ['cannelle', 0.25, 'c.à.c', 'placard']],
    steps: ['Rôtir l\'aubergine en tranches 20 min à 200 °C.', 'Cuire lentilles, oignon, tomates et cannelle 25 min.',
      'Alterner aubergine et lentilles, napper de yaourt battu avec l\'œuf.', 'Cuire 25 min à 180 °C.'],
  }),
  R('gratin-choufleur-pois-chiches', 'Gratin de chou-fleur, brocoli & pois chiches', {
    tags: ['vegetarien'], main: 'legumineuses', time: 45, kcal: 440, keeps: 4, freezable: true,
    ing: [['chou-fleur', 0.25, '', 'legumes'], ['brocoli', 100, 'g', 'legumes'], ['pois chiches cuits', 70, 'g', 'feculents'],
      ['lait demi-écrémé', 100, 'ml', 'cremerie'], ['farine', 10, 'g', 'epicerie'], ['emmental râpé', 20, 'g', 'cremerie']],
    steps: ['Précuire chou-fleur et brocoli 8 min à la vapeur.', 'Préparer une béchamel légère.', 'Mélanger avec les pois chiches, parsemer d\'emmental, 25 min à 200 °C.'],
  }),
  R('veloute-brocoli', 'Velouté de brocoli & lentilles corail', {
    tags: ['vegetarien'], main: 'legumineuses', time: 30, kcal: 380, keeps: 4, freezable: true,
    ing: [['brocoli', 200, 'g', 'legumes'], ['lentilles corail', 40, 'g', 'feculents'], ['oignon', 0.3, '', 'legumes'],
      ['fromage frais', 20, 'g', 'cremerie'], ['bouillon de légumes (cube)', 0.25, '', 'placard'], ['pain complet', 40, 'g', 'feculents']],
    steps: ['Cuire brocoli, lentilles et oignon dans le bouillon 20 min.', 'Mixer avec le fromage frais.', 'Servir avec le pain.'],
  }),
  R('burger-haricots', 'Burgers de haricots rouges & patate douce', {
    tags: ['vegan'], main: 'legumineuses', time: 40, kcal: 560, keeps: 3, freezable: true,
    ing: [['haricots rouges cuits', 100, 'g', 'feculents'], ['patate douce', 80, 'g', 'legumes'], ['flocons d\'avoine', 20, 'g', 'feculents'],
      ['cumin', 0.5, 'c.à.c', 'placard'], ['pain burger complet', 1, '', 'feculents'], ['salade verte', 30, 'g', 'legumes'], ['tomates', 0.5, '', 'legumes']],
    steps: ['Cuire la patate douce, l\'écraser avec les haricots, l\'avoine et le cumin.', 'Former des steaks, cuire 20 min à 200 °C.',
      'Congeler les steaks en trop ; monter les burgers au moment de manger.'],
  }),
  R('salade-boulgour-feta', 'Salade-repas boulgour, lentilles, feta & menthe', {
    tags: ['vegetarien'], main: 'cereales', time: 25, kcal: 520, keeps: 4, freezable: false,
    ing: [['boulgour', 50, 'g', 'feculents'], ['lentilles vertes', 40, 'g', 'feculents'], ['feta', 30, 'g', 'cremerie'],
      ['concombre', 0.3, '', 'legumes'], ['tomates cerises', 80, 'g', 'legumes'], ['menthe fraîche', 0.1, 'botte', 'legumes'],
      ['citron', 0.25, '', 'legumes'], HUILE],
    steps: ['Cuire boulgour et lentilles, refroidir.', 'Ajouter crudités, menthe et feta.', 'Assaisonner citron-huile au moment de servir.'],
  }),
  R('soba-champignons-edamame', 'Nouilles soba sautées, champignons & edamame', {
    tags: ['vegan'], main: 'cereales', time: 20, kcal: 480, keeps: 3, freezable: false,
    ing: [['nouilles soba', 70, 'g', 'feculents'], ['champignons de Paris', 100, 'g', 'legumes'], ['edamame surgelés', 60, 'g', 'surgeles'],
      ['sauce soja', 1, 'c.à.s', 'placard'], ['gingembre frais', 5, 'g', 'legumes'], ['oignon nouveau', 0.5, '', 'legumes']],
    steps: ['Cuire soba et edamame, rincer les soba.', 'Sauter champignons et gingembre.', 'Ajouter nouilles, edamame et soja. Oignon nouveau au service.'],
  }),
  R('dahl-epinards-patate', 'Dahl patate douce & épinards, pain naan complet', {
    tags: ['vegetarien'], main: 'legumineuses', time: 35, kcal: 520, keeps: 5, freezable: true,
    ing: [['lentilles corail', 60, 'g', 'feculents'], ['patate douce', 100, 'g', 'legumes'], ['épinards frais', 60, 'g', 'legumes'],
      ['lait de coco', 40, 'ml', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['garam masala', 1, 'c.à.c', 'placard'], ['pain naan complet', 0.5, '', 'feculents']],
    steps: ['Faire revenir oignon et épices.', 'Ajouter lentilles, patate douce en dés, lait de coco et 2 verres d\'eau ; 20 min.', 'Ajouter les épinards. Servir avec le naan.'],
  }),
  R('shakshuka-verte', 'Shakshuka verte aux épinards & courgette', {
    tags: ['vegetarien', 'sans-gluten'], main: 'oeuf', time: 25, kcal: 380, keeps: 3, freezable: false,
    ing: [['œufs', 2, '', 'cremerie'], ['épinards frais', 100, 'g', 'legumes'], ['courgette', 0.5, '', 'legumes'],
      ['poireau', 0.3, '', 'legumes'], ['feta', 25, 'g', 'cremerie'], ['cumin', 0.5, 'c.à.c', 'placard']],
    steps: ['Préparer la base à l\'avance : poireau, courgette et épinards fondus au cumin.', 'Le jour J : réchauffer, casser les œufs, couvrir 6 min.', 'Émietter la feta.'],
  }),
  R('chili-quinoa-vegan', 'Chili au quinoa, haricots noirs & poivrons', {
    inDish: ['quinoa'], tags: ['vegan', 'sans-gluten'], main: 'legumineuses', time: 40, kcal: 490, keeps: 5, freezable: true,
    ing: [['quinoa', 40, 'g', 'feculents'], ['haricots noirs cuits', 100, 'g', 'feculents'], ['poivron', 0.5, '', 'legumes'],
      ['tomates concassées', 150, 'g', 'epicerie'], ['oignon', 0.5, '', 'legumes'], ['maïs en conserve', 40, 'g', 'epicerie'],
      ['cumin', 1, 'c.à.c', 'placard'], ['paprika fumé', 0.5, 'c.à.c', 'placard']],
    steps: ['Faire revenir oignon, poivron et épices.', 'Ajouter quinoa rincé, tomates et 1 verre d\'eau par portion ; 20 min.', 'Ajouter haricots et maïs, 5 min.'],
  }),
];
